import { storage } from "./storage";

const ADMIN_ID = "seed-admin";

function formatDate(dateStr: string): string {
  const d = new Date(dateStr);
  return d.toLocaleDateString("en-GB", { weekday: "long", day: "numeric", month: "long", year: "numeric" });
}

function ordinal(n: number): string {
  const s = ["th", "st", "nd", "rd"];
  const v = n % 100;
  return n + (s[(v - 20) % 10] || s[v] || s[0]);
}

// Checks if a string appears in a list of recent article titles (case-insensitive, partial match)
function alreadyCovered(recentTitles: string[], phrase: string): boolean {
  const low = phrase.toLowerCase();
  return recentTitles.some(t => t.toLowerCase().includes(low));
}

// Full evergreen topic library — auto-publish cycles through these, skipping any already published
const EVERGREEN_TOPICS = [
  {
    keyword: "DRS",
    title: "DRS Explained: How Formula 1's Overtaking Aid Changed Racing Forever",
    tags: ["Technical", "DRS", "Overtaking", "Explainer"],
    content: `The Drag Reduction System — universally known by its acronym DRS — is one of the most debated pieces of technology in modern Formula 1. Introduced in 2011 as a deliberate mechanism to increase overtaking, it has been celebrated for producing more on-track action and criticised for making passes too easy.\n\nThe system works by allowing the driver following within one second of the car ahead to open a flap in the rear wing, reducing aerodynamic drag and increasing straight-line speed by approximately 10-15 km/h. In that window, the following driver can close the gap enough to attempt an overtake into the next braking zone.\n\nDRS zones are designated by the FIA before each race weekend based on the circuit layout. Most tracks have one or two zones, positioned on the longest straights where top speed has the greatest effect. Monza, with its multiple long straights, has historically offered the most DRS opportunity on the calendar.\n\nThe system can only be activated after the second lap of the race and after a safety car period, ensuring drivers have settled into racing conditions before artificial aids are deployed. In qualifying, drivers can use DRS freely throughout their lap without the one-second restriction.\n\nCritics have argued that DRS has transformed some overtakes from genuinely achieved passes into foregone conclusions — a driver simply pressing a button to sail past on the straight with no defensive option available. Proponents counter that without it, the aerodynamic turbulence generated by modern F1 cars would make following at close range nearly impossible, eliminating wheel-to-wheel racing entirely.\n\nThe 2022 regulation changes, which introduced ground-effect aerodynamics designed to reduce the dirty air problem, were partly intended to eventually reduce reliance on DRS. The discussion about phasing out the system continues in the paddock to this day, and with 2026's new regulations now bedded in, the future of DRS remains one of the sport's most active technical debates.`,
  },
  {
    keyword: "Pit Wall",
    title: "Inside the F1 Pit Wall: The Strategists Who Win Races From a Laptop",
    tags: ["Strategy", "Technical", "Behind the Scenes"],
    content: `For every driver who wins a Formula 1 race on track, there is a team of strategists behind a bank of screens on the pit wall who made it possible. Understanding how the pit wall works — and the decisions it makes under pressure — is essential to understanding the modern sport.\n\nThe race strategist's primary tool is their tyre model. Every team runs sophisticated software that predicts, lap by lap, how their tyres will degrade and what pace the car will be capable of at any given point in the race. This model is fed by live telemetry from the car, historical degradation data from previous races at the same circuit, and the weather feed from trackside sensors.\n\nFrom this data, the strategist constructs multiple race scenarios before lights out — a one-stop strategy, a two-stop, an alternative compound sequence — and ranks them by projected finishing position. As the race develops and variables change (safety cars, weather shifts, rival strategies), the model is updated in real time and the strategist communicates through the driver's ear.\n\nThe most critical moments are those that cannot be pre-planned: the unexpected safety car, the rival who pits a lap earlier than predicted, the sudden rain shower. In these moments, the strategist has seconds to make calls that could determine the championship. The best in the business make these calls with a combination of data confidence and instinct that takes years to develop.\n\nIn a modern F1 race, the margin between first and fourth can be as small as a single strategic call made correctly under pressure. The pit wall is where championships are decided.`,
  },
  {
    keyword: "Tyre Compounds",
    title: "Pirelli's F1 Tyre Compounds Explained: From Soft to Hard and Everything Between",
    tags: ["Technical", "Tyres", "Pirelli", "Explainer"],
    content: `Pirelli has been Formula 1's sole tyre supplier since 2011, and the Italian manufacturer's compounds have been one of the defining elements of race strategy throughout that period. Understanding how the tyre range works is fundamental to understanding why races unfold the way they do.\n\nFor each grand prix, Pirelli nominates three compounds from their range — designated C1 through C5, where C1 is the hardest and C5 the softest. These are then labelled for race weekend use as Hard, Medium, and Soft respectively. The specific selection varies by circuit: at high-energy tracks like Silverstone, Pirelli typically brings harder compounds; at lower-stress circuits like Monaco, softer compounds are used.\n\nThe trade-off is straightforward in principle, complex in execution. Softer compounds generate more grip and therefore more pace, but their rubber degrades faster as they heat and wear. Harder compounds sacrifice some outright pace for greater durability — they can cover significantly more laps before their performance falls off a cliff.\n\nThe degradation model is not linear. Tyres typically go through three phases: a warming phase where performance builds, a performance peak, and then a degradation phase that can vary from gradual to sudden. Predicting and managing this cliff is one of the most demanding aspects of race strategy.\n\nThermal management — keeping the tyre within its optimal operating temperature window — is a constant challenge. Too cold, and the rubber doesn't generate sufficient grip. Too hot, and the tyre blisters and degrades rapidly. The introduction of 18-inch wheels in 2022 changed the thermal properties of F1 tyres significantly, running cooler and less prone to the dramatic overheating that characterised the earlier era.`,
  },
  {
    keyword: "Downforce",
    title: "Downforce: The Invisible Force That Makes F1 Cars Defy Physics",
    tags: ["Technical", "Aerodynamics", "Explainer"],
    content: `A modern Formula 1 car generates more aerodynamic downforce than its own weight. At racing speeds, the aerodynamic load pressing the car into the ground exceeds the force of gravity acting upon it. In theoretical terms, at sufficient speed, an F1 car could drive upside down on the ceiling of a tunnel and stay there.\n\nDownforce is generated primarily by the interaction between airflow and shaped surfaces. The wings at the front and rear of the car function as inverted aerofoils — the same principle as an aircraft wing, but inverted to generate downward force rather than lift. The angle of these wings (their "angle of attack") determines how much downforce they generate, but also how much drag they create.\n\nThis is the fundamental compromise at the heart of F1 car design: more downforce means more corner grip and faster lap times through high-speed sections, but also more drag and slower straight-line speed. Every circuit demands a different balance. At Monza, teams run minimum downforce for maximum top speed. At Monaco, maximum downforce is required for the slow, technical corners.\n\nThe 2022 regulations represented a revolution in how downforce is generated. Previous cars relied heavily on complex front wing endplates and bargeboards to control airflow. The new ground-effect regulations moved the downforce generation beneath the car through shaped underfloor channels — sucking it downwards. Ground-effect downforce is considered more efficient because it creates less drag for equivalent grip levels, and is less affected by disturbed air, allowing cars to follow more closely.`,
  },
  {
    keyword: "F1 Budget Cap",
    title: "The F1 Cost Cap Explained: How the $135 Million Limit Reshaped the Paddock",
    tags: ["Regulations", "Budget Cap", "Business of F1"],
    content: `When Formula 1 introduced a financial cost cap in 2021, it represented the most significant structural change to the sport's economics in its history. The intent was simple: prevent the wealthiest teams from spending their way to dominance, and create conditions where technical excellence and innovation mattered more than raw financial firepower.\n\nThe cap limits the amount teams can spend on performance-related costs — essentially, anything directly connected to developing and racing the car. The figure has been set at varying levels since introduction, sitting in the region of $135 million for the current cycle.\n\nCrucially, certain costs are excluded from the cap: driver salaries above a threshold, the salaries of the three highest-paid staff members, marketing costs, and the CEO's salary. This means total spending at a top team remains significantly higher than the headline cap figure.\n\nThe FIA enforces the cap through detailed financial scrutiny. The process has not been without controversy — Red Bull Racing's breach of the 2021 cap resulted in a significant fine and aerodynamic testing penalty. The impact on the midfield has been arguably the cap's most transformative effect, with far smaller gaps between teams than existed before 2021.`,
  },
  {
    keyword: "Safety Car",
    title: "The Safety Car in Formula 1: Strategy, Controversy and Why It Matters",
    tags: ["Strategy", "Safety Car", "Regulations", "Explainer"],
    content: `The safety car is one of the most powerful instruments in Formula 1 racing — and one of the most strategically significant. Deployed whenever an incident on track creates conditions deemed too dangerous for racing, the safety car neutralises the field and closes up gaps that may have taken an entire race distance to build.\n\nFor teams at the front, a well-timed safety car is a gift: pit stops can be made with minimal time loss, freeing them to run to the end of the race on fresh rubber. For teams who have just pitted, it can be a disaster — suddenly the gap they gained is gone and a rival on old tyres finds themselves ahead on the road.\n\nThe virtual safety car (VSC), introduced in 2015, allows the race to be neutralised without physically deploying the actual safety car onto the circuit. Under VSC conditions, all drivers must maintain a fixed delta time — typically around 40% slower than racing pace — rather than following the safety car directly.\n\nThe most controversial moment in recent safety car history came at the 2021 Abu Dhabi Grand Prix, when the decision to allow only some lapped cars to unlap themselves before the restart — rather than all of them — set up the final lap battle that decided the world championship between Lewis Hamilton and Max Verstappen. The FIA's subsequent investigation resulted in clarified procedures designed to prevent any ambiguity in future deployments.\n\nFor fans, safety car periods remain among the most tensely watched moments in any grand prix — pivotal, unpredictable, and often decisive.`,
  },
  {
    keyword: "Qualifying Format",
    title: "How F1 Qualifying Works: The Complete Guide to Q1, Q2, Q3 and Sprint",
    tags: ["Explainer", "Qualifying", "Format", "Regulations"],
    content: `Qualifying in Formula 1 is a knockout competition spread across three separate sessions that produces the grid order for the following day's race. Understanding how it works — and the strategic decisions it forces — is key to appreciating the full depth of a Formula 1 weekend.\n\nQ1 lasts 18 minutes and involves all 20 cars. The five slowest drivers are eliminated and take positions 16-20 on the grid. Q2 follows immediately with 15 drivers and lasts 15 minutes — the five slowest are again eliminated, taking positions 11-15. Q3 is the final 12-minute shootout between the ten remaining drivers to determine the top ten grid positions.\n\nA critical strategic wrinkle is the tyre rule: drivers who progress from Q2 to Q3 are required to start the race on the same compound they set their fastest Q2 lap on. This creates a genuine dilemma — teams may choose to use the faster Soft compound in Q2 to guarantee progression, knowing they will start the race on a tyre that degrades more rapidly. Others may gamble on the Medium, betting that their Q2 lap time is fast enough to reach Q3 and that a better race strategy on harder rubber will compensate.\n\nOn Sprint weekends, a shortened 60-minute Sprint Shootout on Friday replaces the traditional qualifying format for the Sprint race grid. Standard qualifying then determines Sunday's race grid. The Sprint race itself, held on Saturday, offers up to 8 championship points and runs for approximately one third of the full race distance.`,
  },
  {
    keyword: "F1 Points System",
    title: "The F1 Points System Explained: How Championships Are Won and Lost",
    tags: ["Explainer", "Points System", "Championship", "Regulations"],
    content: `The Formula 1 points system is the mechanism by which a season of 24 separate races is compressed into a single championship hierarchy. Points are awarded to the top ten finishers after each grand prix, with the winner receiving 25 points and the scale descending to a single point for tenth place.\n\nThe current points distribution — 25, 18, 15, 12, 10, 8, 6, 4, 2, 1 — has been in use since 2010. A bonus point is also awarded for the fastest lap in the race, but only to a driver finishing in the top ten. On Sprint weekends, an additional smaller points allocation (8, 7, 6, 5, 4, 3, 2, 1) is awarded for the top eight finishers in the Sprint race.\n\nThe system is designed to reward consistency as much as outright race victories. A driver who finishes second in every race will outscore a driver who wins half the races but retires from the rest. This has historically made reliability as important a factor as raw pace in championship mathematics.\n\nThe Constructors' Championship — run simultaneously with the Drivers' Championship — awards points to teams based on the combined finishes of both their drivers. This creates scenarios where team tactics, including team orders, can become relevant: if one driver is leading the Constructors' Championship battle, the team may ask the other driver to yield position to maximise points.`,
  },
  {
    keyword: "Monaco Grand Prix",
    title: "Monaco: Why Formula 1's Most Famous Race Is Unlike Any Other",
    tags: ["Monaco", "Street Circuit", "F1 History", "Circuits"],
    content: `Monaco is unlike any other Formula 1 race. The circuit through the narrow streets of the Principality has been on the World Championship calendar since 1955, making it not only the most famous but also one of the oldest races in the sport's history. To win at Monaco is to join a pantheon of legends.\n\nThe circuit itself is a paradox in modern Formula 1. At just 3.337 kilometres, it is the shortest on the calendar. Its corners are slow, its run-off non-existent, and its barriers are so close that drivers routinely clip the armco on flying laps. A modern F1 car, designed to generate enormous downforce at high speeds, is poorly suited to Monaco's slow-speed layout — and yet it remains the race every driver most wants to win.\n\nOvertaking at Monaco is almost impossible. With such narrow roads and no long straights, the race is often decided by qualifying, pit stop timing, and safety car strategy rather than wheel-to-wheel battles. This is why Monaco qualifying has a special character — a single tenth of a second over a 3.3 kilometre lap can mean the difference between pole and the pitlane at the start.\n\nAyrton Senna won Monaco six times, a record that reflects not just pace but a particular sensitivity for street circuits that bordered on the supernatural. His 1984 charge through the streets in a midfield Toleman before the race was red-flagged remains one of the defining moments in the sport's history.\n\nIn the modern era, debate continues about whether Monaco's lack of overtaking makes it a poor spectacle. Yet the race weekend consistently generates the largest television audience on the F1 calendar. Some traditions resist the march of data.`,
  },
  {
    keyword: "F1 Car Weight",
    title: "Why F1 Cars Have Gotten Heavier — And Why It Matters",
    tags: ["Technical", "Regulations", "Car Design", "Weight"],
    content: `In 1950, a Formula 1 car weighed around 700 kilograms. Today, the minimum weight limit sits at 798 kilograms including the driver. This near-doubling over 75 years might seem counterintuitive for a sport defined by performance, but the reasons behind the trend reveal much about how F1 has changed.\n\nThe primary driver of increasing weight is safety. The carbon fibre survival cell that protects modern drivers, the halo structure above the cockpit, the mandatory side impact structures, the fuel system and fire suppression equipment — all of these add kilograms that did not exist in the sport's early decades. The halo alone weighs around 7 kilograms. The overall chassis, by contrast, weighs less than 40 kilograms thanks to carbon fibre construction.\n\nHybrid power units introduced in 2014 added significant mass. The battery, the motor generator units, and the associated cooling systems can add 50 kilograms compared to a pure combustion engine. The performance benefits — the electrical deployment now generating over 400kW in 2026 — more than compensate in lap time terms.\n\nWheel size is another factor. The move from 13-inch to 18-inch wheels in 2022 brought heavier tyres and rims, contributing to an increase in the minimum weight limit.\n\nFor drivers, the weight regulations have created a distinct advantage for taller, heavier physiques — a reversal of the historical trend where the lightest drivers enjoyed a natural advantage. The regulations allow teams to add ballast up to the minimum weight, which they place strategically for ideal weight distribution. Smaller drivers who come in well under the weight limit effectively gift their team this ballast placement freedom.`,
  },
  {
    keyword: "F1 Teams History",
    title: "The Rise and Fall of F1 Teams: From Legends to Forgotten Names",
    tags: ["F1 History", "Teams", "Paddock"],
    content: `Formula 1 has seen more than a hundred different constructors take to the grid since the World Championship began in 1950. Of those, only a handful survive today. The story of F1 teams is one of ambition, brilliance, financial pressure, and — for many — eventual failure.\n\nThe greatest survivor is Ferrari, who have competed in every season of the World Championship without exception. The Scuderia won their first Constructors' title in 1961 and their most recent in 2008. For all the years of struggle in between, Ferrari's presence on the grid is so central to the sport's identity that they receive a unique annual payment simply for being there.\n\nMcLaren entered Formula 1 in 1966 and have won 183 races — second only to Ferrari in the all-time list. Their dominant period in the late 1980s, when Ayrton Senna and Alain Prost won 15 of 16 races in the 1988 season, remains the benchmark against which all subsequent dominance is measured.\n\nThe failures tell equally compelling stories. Brabham won two Constructors' Championships and produced some of the sport's most innovative cars before disappearing in 1992. Tyrrell won the 1971 championship with Jackie Stewart, produced a six-wheeled car in 1976, and was absorbed into British American Racing in 1998. More recently, HRT, Caterham, and Marussia all entered the sport during the 2010 expansion — and all had folded within five years.\n\nThe economics of Formula 1 remain brutal. The cost cap has improved the situation for surviving teams, but the barrier to entry remains enormous and the consequences of a single bad season, combined with a loss of sponsorship, can be terminal.`,
  },
  {
    keyword: "Fastest Lap Record",
    title: "F1's Fastest Laps: The Records, the Circuits and the Drivers Who Set Them",
    tags: ["Records", "Speed", "F1 History", "Technical"],
    content: `Speed is the essence of Formula 1, and the lap records set at each circuit on the calendar represent the absolute limit of what a driver and car can achieve together. These records are a snapshot of technical progress — and comparing them across eras tells the story of the sport's development.\n\nThe outright speed records in Formula 1 were set in the turbo era of the early 1980s. At qualifying trim, some cars of that period were estimated to produce over 1,400 horsepower from 1.5-litre turbocharged engines. The lap records they set at circuits like Hockenheim — since modified — have never been equalled.\n\nAt circuits still in their original form, lap record comparisons are illuminating. The modern cars, for all their technological sophistication, are often slower over a single lap than the unrestricted turbo cars of the 1980s. However, they are faster than anything seen between 1989 (when turbo engines were banned) and 2021.\n\nThe race lap record — as opposed to the qualifying lap record — is the faster lap set by any driver during a race. The current points system awards a bonus championship point for the fastest race lap, provided the driver finishes in the top ten. This has led to a tactical element where teams send drivers to pit for fresh tyres late in the race specifically to target the fastest lap point.\n\nMonza remains the circuit where F1 cars reach their highest speeds: top speeds exceeding 365 km/h have been recorded on the main straight during race weekends. The combination of low-downforce setup and long straights makes it unique on the calendar.`,
  },
];

export async function generateAndPublishArticle(): Promise<{
  success: boolean;
  title?: string;
  message?: string;
  noContent?: boolean;
}> {
  try {
    const today = new Date();
    const todayStr = today.toISOString().split("T")[0];

    // Load all existing articles (published + pending) to check what's already been done
    const [published, pending] = await Promise.all([
      storage.getArticles(),
      storage.getPendingArticles(),
    ]);
    const allArticles = [...published, ...pending];

    // Has an auto-article already been submitted TODAY? (avoid duplicates within the same day)
    const alreadyToday = allArticles.some((a: any) => {
      const dateField = a.publishedAt || a.createdAt;
      const date = dateField ? new Date(dateField).toISOString().split("T")[0] : "";
      return date === todayStr && a.authorId === ADMIN_ID;
    });
    if (alreadyToday) {
      return { success: false, message: "An article was already auto-submitted today. Come back tomorrow." };
    }

    // Build a set of recent auto-published titles (last 90 days) for deduplication
    const cutoff = new Date(today.getTime() - 90 * 24 * 60 * 60 * 1000);
    const recentAutoTitles = allArticles
      .filter((a: any) => {
        if (a.authorId !== ADMIN_ID) return false;
        const dateField = a.publishedAt || a.createdAt;
        return dateField ? new Date(dateField) > cutoff : false;
      })
      .map((a: any) => a.title as string);

    // Load live data
    const [races, drivers, constructors] = await Promise.all([
      storage.getAllRaces(2026),
      storage.getDriverStandings(2026),
      storage.getConstructorStandings(2026),
    ]);

    const nowMs = today.getTime();
    const upcoming = races
      .filter((r) => r.status === "upcoming" || r.status === "live")
      .sort((a, b) => new Date(a.raceDate).getTime() - new Date(b.raceDate).getTime());
    const completed = races
      .filter((r) => r.status === "completed")
      .sort((a, b) => new Date(b.raceDate).getTime() - new Date(a.raceDate).getTime());

    const nextRace = upcoming[0];
    const lastRace = completed[0];
    const top3Drivers = drivers.slice(0, 3);
    const top2Constructors = constructors.slice(0, 2);

    let articleData: { title: string; excerpt: string; content: string; tags: string[]; sortOrder: number } | null = null;

    // Priority 1: Race preview — if a race is within 7 days and we haven't previewed it yet
    if (nextRace) {
      const daysUntil = Math.ceil((new Date(nextRace.raceDate).getTime() - nowMs) / (1000 * 60 * 60 * 24));
      if (daysUntil >= 0 && daysUntil <= 7 && !alreadyCovered(recentAutoTitles, nextRace.name + " Preview")) {
        const leader = top3Drivers[0];
        const second = top3Drivers[1];
        const ptsDiff = leader && second ? leader.points - second.points : 0;
        const topConstructor = top2Constructors[0];
        const driverBattle = leader && second
          ? `${leader.driverName} leads the Drivers' Championship with ${leader.points} points, ${ptsDiff} ahead of ${second.driverName}.`
          : "";
        const teamBattle = topConstructor
          ? `In the Constructors' standings, ${topConstructor.teamName} lead the way with ${topConstructor.points} points.`
          : "";

        articleData = {
          title: `${nextRace.name} Preview: Everything You Need to Know Ahead of Round ${nextRace.round}`,
          excerpt: `Formula 1 heads to ${nextRace.location}, ${nextRace.country} for the ${nextRace.name}. With the championship picture sharpening, this could be a pivotal weekend. Here is everything you need to know.`,
          tags: [nextRace.country, "Race Preview", "2026 Season", nextRace.name],
          sortOrder: 10,
          content: `Formula 1 returns to action this weekend at ${nextRace.circuit} in ${nextRace.location}, ${nextRace.country} for the ${nextRace.name} — Round ${ordinal(nextRace.round)} of the 2026 World Championship. ${nextRace.hasSprint ? "This is a Sprint weekend, with an additional Sprint race on Saturday that adds a further 8 points to the championship tally." : ""}\n\n## The Championship Situation\n\n${driverBattle} ${teamBattle} With ${upcoming.length} rounds remaining after this weekend, every point counts and the pressure on the drivers to perform will be intense.\n\n## Circuit Profile: ${nextRace.circuit}\n\nLocated in ${nextRace.location}, ${nextRace.country}, the ${nextRace.circuit} is one of the most demanding venues on the 2026 calendar. The track rewards a precise setup balance between downforce for the technical sections and aerodynamic efficiency for the straights. Getting tyre management right will be critical — teams will be carefully studying their compounds allocation for this event in the days leading up to qualifying.\n\n## Key Questions Heading In\n\nWhich team has found the better setup direction this weekend? Can the championship leader maintain their form under the pressure of a rival closing in? Will the circuit characteristics suit any particular team's car concept in a way that could upset the expected order?\n\nThe answers begin on Friday morning when Practice 1 gets underway. ${nextRace.raceDate ? `The race starts on ${formatDate(nextRace.raceDate)}.` : ""}\n\n## How to Follow the Action\n\nFull live coverage and race analysis will be available here on F1 Fan Hub throughout the weekend. Check back for qualifying reaction, race preview updates, and post-race reports as soon as the chequered flag falls.`,
        };
      }
    }

    // Priority 2: Post-race digest — if a race completed within 4 days and we haven't covered it
    if (!articleData && lastRace) {
      const daysSince = Math.ceil((nowMs - new Date(lastRace.raceDate).getTime()) / (1000 * 60 * 60 * 24));
      if (daysSince >= 0 && daysSince <= 4 && !alreadyCovered(recentAutoTitles, lastRace.name + " Reaction")) {
        const leader = top3Drivers[0];
        const second = top3Drivers[1];
        const topTeam = top2Constructors[0];

        articleData = {
          title: `${lastRace.name} Reaction: How the Standings Look After Round ${lastRace.round}`,
          excerpt: `With the ${lastRace.name} in the books, we take stock of the championship picture. Here is how the 2026 season standings look after ${ordinal(lastRace.round)} round.`,
          tags: [lastRace.country, "Standings", "2026 Season", lastRace.name],
          sortOrder: 10,
          content: `The ${lastRace.name} at ${lastRace.circuit} has added another chapter to the 2026 Formula 1 season story. As the paddock takes stock after ${ordinal(lastRace.round)} round, the championship picture is becoming clearer.\n\n## How the Drivers' Championship Stands\n\n${top3Drivers.map((d, i) => `**${ordinal(i + 1)}. ${d.driverName} (${d.teamName}) — ${d.points} points**`).join("\n")}\n\n${leader && second ? `${leader.driverName} holds ${leader.points - second.points} points of advantage over ${second.driverName}. The gap ${leader.points - second.points < 10 ? "remains tight enough that a single bad weekend could change everything" : "gives the championship leader some breathing room, but nothing is settled yet"}.` : ""}\n\n## The Constructors' Battle\n\n${top2Constructors.map((c, i) => `**${ordinal(i + 1)}. ${c.teamName} — ${c.points} points**`).join("\n")}\n\n${topTeam ? `${topTeam.teamName} lead the Constructors' Championship, a reflection of consistent points scoring from both drivers throughout the opening rounds.` : ""}\n\n## Looking Ahead\n\n${upcoming.length > 0 ? `The next round is the ${upcoming[0].name} at ${upcoming[0].circuit} in ${upcoming[0].location}. With ${upcoming.length} races still to run, the 2026 championship remains very much in play for multiple contenders.` : "The 2026 season continues to build towards what promises to be a dramatic conclusion."}\n\nKeep up with all the action here on F1 Fan Hub — analysis, race previews, and live standings updates throughout the 2026 campaign.`,
        };
      }
    }

    // Priority 3: Mid-week standings digest (Tue/Wed), not already published this week
    if (!articleData && (today.getDay() === 2 || today.getDay() === 3) && top3Drivers.length > 0) {
      const weekAgo = new Date(today.getTime() - 7 * 24 * 60 * 60 * 1000);
      const standingsThisWeek = allArticles.some((a: any) => {
        const dateField = a.publishedAt || a.createdAt;
        if (!dateField) return false;
        const pub = new Date(dateField);
        return pub > weekAgo && a.authorId === ADMIN_ID && (a.title || "").toLowerCase().includes("standings");
      });

      if (!standingsThisWeek) {
        const leader = top3Drivers[0];
        const second = top3Drivers[1];
        const third = top3Drivers[2];

        articleData = {
          title: `2026 F1 Championship Standings: Where Every Driver and Team Stands Now`,
          excerpt: `The 2026 Formula 1 season is underway. Here is a full breakdown of the Drivers' and Constructors' Championship standings as they look right now.`,
          tags: ["Standings", "2026 Season", "Championship"],
          sortOrder: 10,
          content: `With ${completed.length} rounds of the 2026 Formula 1 World Championship completed and ${upcoming.length} still to come, the picture is becoming clearer — though the outcome remains far from decided. Here is a comprehensive look at exactly where every driver and team stands.\n\n## Drivers' Championship — Top 10\n\n${drivers.slice(0, 10).map((d, i) => `**${ordinal(i + 1)}. ${d.driverName} ${d.flagEmoji || ""} (${d.teamName}) — ${d.points} pts${d.wins > 0 ? ` | ${d.wins} win${d.wins > 1 ? "s" : ""}` : ""}`).join("\n")}\n\n${leader && second ? `The gap between ${leader.driverName} and ${second.driverName} currently stands at ${leader.points - second.points} points — the equivalent of ${Math.ceil((leader.points - second.points) / 25)} race victories at maximum score. ${third ? `${third.driverName} is a further ${second.points - third.points} back in third.` : ""}` : ""}\n\n## Constructors' Championship\n\n${constructors.map((c, i) => `**${ordinal(i + 1)}. ${c.teamName} — ${c.points} pts`).join("\n")}\n\n## Season in Numbers\n\n- Rounds completed: ${completed.length}\n- Rounds remaining: ${upcoming.length}\n\n${upcoming.length > 0 ? `The next race is the **${upcoming[0].name}** at ${upcoming[0].circuit}${upcoming[0].raceDate ? ` on ${formatDate(upcoming[0].raceDate)}` : ""}.` : ""}\n\nF1 Fan Hub will keep this page updated as the season develops — check back after every race for the latest standings.`,
        };
      }
    }

    // Priority 4: Evergreen topic rotation — pick the next topic not yet published
    if (!articleData) {
      const availableTopic = EVERGREEN_TOPICS.find(
        (t) => !alreadyCovered(recentAutoTitles, t.keyword)
      );

      if (availableTopic) {
        articleData = {
          title: availableTopic.title,
          excerpt: availableTopic.content.split("\n")[0].substring(0, 200) + "...",
          tags: availableTopic.tags,
          sortOrder: 30,
          content: availableTopic.content,
        };
      }
    }

    // Nothing available — all content types already covered recently
    if (!articleData) {
      const nextRaceName = upcoming[0]?.name || "the next race";
      return {
        success: false,
        noContent: true,
        message: `All evergreen topics have been published recently and there's no upcoming race to preview right now. New content will be available closer to ${nextRaceName}, or try again tomorrow.`,
      };
    }

    // Submit for admin review
    const submitted = await storage.submitArticle({
      title: articleData.title,
      excerpt: articleData.excerpt,
      content: articleData.content,
      authorId: ADMIN_ID,
      section: "news",
      tags: articleData.tags,
      sortOrder: articleData.sortOrder,
      imageUrl: null,
    });

    return { success: true, title: submitted.title };
  } catch (err: any) {
    return { success: false, message: err?.message || "Unknown error" };
  }
}
