import { storage } from "./storage";

const ADMIN_ID = "seed-admin";
const MAX_PER_DAY = 5;

// Curated motorsport/F1 images from Unsplash CDN (stable public URLs)
const IMGS = {
  aero: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=1200&q=80",
  track: "https://images.unsplash.com/photo-1541348263662-e068662d82af?auto=format&fit=crop&w=1200&q=80",
  car: "https://images.unsplash.com/photo-1547124010-9f501dc2ec65?auto=format&fit=crop&w=1200&q=80",
  pit: "https://images.unsplash.com/photo-1607603750909-408e193868c7?auto=format&fit=crop&w=1200&q=80",
  tyre: "https://images.unsplash.com/photo-1621135802920-133df287f89c?auto=format&fit=crop&w=1200&q=80",
  tech: "https://images.unsplash.com/photo-1580894732444-8ecded7900cd?auto=format&fit=crop&w=1200&q=80",
  cockpit: "https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?auto=format&fit=crop&w=1200&q=80",
  speed: "https://images.unsplash.com/photo-1504215680853-026ed2a45def?auto=format&fit=crop&w=1200&q=80",
  circuit: "https://images.unsplash.com/photo-1507035895480-2b3156c31fc8?auto=format&fit=crop&w=1200&q=80",
  helmet: "https://images.unsplash.com/photo-1614518921673-2b010ac3d5cd?auto=format&fit=crop&w=1200&q=80",
  data: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80",
  carbon: "https://images.unsplash.com/photo-1567761616-a178fd05d9c5?auto=format&fit=crop&w=1200&q=80",
};

function formatDate(dateStr: string): string {
  return new Date(dateStr).toLocaleDateString("en-GB", { weekday: "long", day: "numeric", month: "long", year: "numeric" });
}

function ordinal(n: number): string {
  const s = ["th", "st", "nd", "rd"];
  const v = n % 100;
  return n + (s[(v - 20) % 10] || s[v] || s[0]);
}

function alreadyCovered(recentTitles: string[], phrase: string): boolean {
  const low = phrase.toLowerCase();
  return recentTitles.some(t => t.toLowerCase().includes(low));
}

interface Topic {
  keyword: string;
  title: string;
  tags: string[];
  imageUrl: string;
  content: string;
}

const TECHNICAL_TOPICS: Topic[] = [
  {
    keyword: "DRS",
    title: "DRS Explained: How Formula 1's Overtaking Aid Changed Racing Forever",
    tags: ["Technical", "DRS", "Aerodynamics", "Explainer"],
    imageUrl: IMGS.aero,
    content: `The Drag Reduction System — universally known as DRS — is one of the most consequential and debated pieces of technology in modern Formula 1. Introduced in 2011 to increase overtaking, it works by allowing a following driver within one second of the car ahead to open a flap in the rear wing, reducing aerodynamic drag and increasing top speed by approximately 12–15 km/h.\n\nDRS zones are designated by the FIA before each race based on the circuit layout. Most tracks have one or two zones on the longest straights. Monza — with multiple long straights — has historically offered the highest DRS activation frequency on the calendar. Zones have start and end detection points; the system only activates between these markers.\n\nThe activation rules exist specifically to control deployment. Drivers cannot use DRS until lap three of the race, nor in the first two laps after a safety car period ends. In qualifying, DRS can be deployed freely at any time on any part of the circuit — contributing to the gap between qualifying times and race pace.\n\nCritics argue DRS turns some passes into formalities: a driver presses a button, gains straight-line speed that the defending driver cannot match, and sails past into the braking zone with no genuine contest. Supporters counter that without it, the dirty air generated by modern high-downforce cars would make following within two seconds nearly impossible, eliminating wheel-to-wheel racing entirely.\n\nThe 2022 ground-effect regulations reduced reliance on DRS by generating more downforce under the car than over it — meaning cars could follow more closely in disturbed air. The FIA signalled interest in phasing DRS out as the regulations matured, making its long-term future one of the sport's live technical debates.`,
  },
  {
    keyword: "Pit Wall Strategy",
    title: "Inside the F1 Pit Wall: How Race Strategy Is Decided in Seconds",
    tags: ["Strategy", "Technical", "Behind the Scenes", "Pit Wall"],
    imageUrl: IMGS.pit,
    content: `For every driver who wins a Formula 1 race on track, there is a team of strategists on the pit wall who made it happen. Understanding how the pit wall operates — and the tools it uses — is essential to understanding modern F1.\n\nThe race strategist's primary tool is a tyre degradation model, updated lap by lap in real time using live telemetry from the car, historical data from previous events at the same circuit, and weather sensor feeds. From this model, the strategist constructs multiple race scenarios before lights out — one-stop, two-stop, alternative compound sequences — and ranks them by projected finishing position.\n\nAs the race unfolds, every variable that changes triggers a model update: a safety car neutralising the field, a rival team making an unexpected pit call, a sudden rain shower, a slow out-lap from a different team. The strategist has seconds — sometimes less — to recalculate and communicate a decision to the driver.\n\nDriver-strategist communication is its own skill. The pit wall might need to ask a driver to hold position to protect a tyre, while the driver — feeling the car behind breathing down their neck — wants to push. Maintaining driver confidence while delivering strategically necessary instructions requires a combination of clear data communication and psychological awareness that takes years to develop.\n\nThe best race strategists in the paddock are known by their peers as people who can hold multiple race scenarios simultaneously in their heads, react to live events instantly, and back their models even when intuition might suggest otherwise. In a modern grand prix, the winning margin between first and fifth can be a single strategically correct call made under pressure.`,
  },
  {
    keyword: "Pirelli Tyre",
    title: "Pirelli's F1 Compounds Explained: The Science Behind Soft, Medium and Hard",
    tags: ["Technical", "Tyres", "Pirelli", "Explainer"],
    imageUrl: IMGS.tyre,
    content: `Pirelli has been Formula 1's sole tyre supplier since 2011. Their compound range — designated C1 through C5, where C1 is hardest and C5 softest — determines the strategic shape of every grand prix weekend. Understanding how the compounds work, and why their selection matters, reveals much about F1 strategy.\n\nFor each round, Pirelli nominates three adjacent compounds from their range and labels them Hard, Medium, and Soft. The specific selection varies by circuit energy level: high-energy tracks like Silverstone or Spa get harder compounds; lower-stress circuits like Monaco or Singapore get softer ones.\n\nThe core trade-off is straightforward: softer compounds generate more grip and pace, but degrade faster. Harder compounds last significantly longer but sacrifice pure speed. Teams must balance peak performance against strategic flexibility — choosing when to pit and which compound to use for each stint.\n\nTyre degradation is not linear. Compounds go through a warm-up phase, a performance peak, and then a degradation phase that can be gradual or sudden. The sudden end of a compound's working range — the "cliff" — is one of the most challenging elements to predict. Crossing it by even one lap can cause lap time losses of two to four seconds per lap as grip disappears rapidly.\n\nThermal management is continuous. Too cold and the compound won't generate sufficient mechanical grip. Too hot and the rubber blisters, chunks, or degrades catastrophically. Driving style, track surface texture, ambient temperature, and car setup all affect tyre temperature simultaneously.\n\nThe 2022 switch from 13-inch to 18-inch wheels fundamentally changed F1 tyre behaviour. The lower-profile sidewall of the 18-inch construction runs at lower operating temperatures, reducing the dramatic overheating failures that characterised parts of the earlier era.`,
  },
  {
    keyword: "Downforce Aerodynamics",
    title: "How F1 Downforce Works: Ground Effect, Wings and the Physics of Grip",
    tags: ["Technical", "Aerodynamics", "Downforce", "Explainer"],
    imageUrl: IMGS.aero,
    content: `A modern Formula 1 car generates more aerodynamic downforce than its own weight at racing speeds. This extraordinary capability — allowing corners to be taken at forces that seemed physically impossible a generation ago — is the result of decades of aerodynamic development across three distinct technical philosophies.\n\nThe first philosophy is **wing-generated downforce**. Front and rear wings function as inverted aerofoils — identical in principle to aircraft wings, but oriented to generate downward rather than upward force. The angle of attack determines the downforce level; steeper angles produce more grip but dramatically increase drag. Every circuit demands a different balance. Monza requires minimum wing for maximum straight-line speed; Monaco needs maximum wing for its slow technical corners.\n\nThe second is **bodywork management**. The bargeboards, sidepod inlets, and turning vanes that characterised F1 cars from the 1990s through 2021 were designed to control the chaotic airflow between front and rear. Their purpose was to guide clean, fast-moving air to the rear diffuser and keep turbulent air away from sensitive aerodynamic surfaces.\n\nThe third — and most powerful — is **ground effect**, rediscovered by the 2022 regulations after being banned in the early 1980s. Shaped underfloor channels accelerate air beneath the car, creating an area of low pressure that literally sucks the car downward. Ground-effect downforce is more efficient than wing-generated downforce because it creates less drag for equivalent grip levels. Crucially, it is also less sensitive to the turbulent air generated by the car ahead — which is why close racing improved noticeably after 2022.\n\nThe total aerodynamic load on an F1 car at 300 km/h is estimated at over 3,500 kilograms. The tyres, suspension, and structural components must resist this load continuously while absorbing racing impacts. Managing this load efficiently across the entire speed range is the defining challenge of modern F1 car design.`,
  },
  {
    keyword: "Hybrid Power Unit",
    title: "The F1 Hybrid Power Unit Explained: How 1,000 Horsepower Is Generated",
    tags: ["Technical", "Power Unit", "Hybrid", "Engineering"],
    imageUrl: IMGS.tech,
    content: `The Formula 1 power unit is the most sophisticated internal combustion system ever put into production racing. Since 2014, F1 has used a 1.6-litre turbocharged V6 engine paired with two motor generator units — a system that produces approximately 1,000 horsepower while recovering more than 50% of the fuel's energy, triple the efficiency of a standard road car.\n\nThe **MGU-K** (Motor Generator Unit — Kinetic) is directly connected to the crankshaft. Under braking, it acts as a generator, converting kinetic energy into electrical energy stored in the battery. Under acceleration, it acts as a motor, deploying stored electrical energy to supplement the combustion engine. The 2014-2025 MGU-K was limited to 120kW of deployment; the 2026 regulations removed this cap, with deployment now exceeding 400kW.\n\nThe **MGU-H** (Motor Generator Unit — Heat), used from 2014 to 2025, recovered energy from the exhaust gases passing through the turbocharger. It was one of the most technically complex and expensive elements of the power unit — and one of the reasons why F1's hybrid systems never made it directly to road cars. The 2026 regulations eliminated the MGU-H entirely in favour of a simplified, more deployable electrical architecture.\n\nThe **turbocharger** uses exhaust gases to spin a compressor, forcing more air into the engine than it could naturally aspirate. The compressed air allows more fuel to be burned per cycle, producing significantly more power than the engine displacement would suggest. Managing the thermal load of the turbo — which operates at temperatures exceeding 1,000°C — is one of the power unit manufacturer's primary development challenges.\n\nThe **battery** (Energy Store) manages electrical flow between the MGUs. Storing exactly the right amount of energy for deployment at the right moment requires software algorithms of extraordinary sophistication. Teams develop their own energy management strategies that are closely guarded intellectual property.`,
  },
  {
    keyword: "F1 Carbon Fibre",
    title: "Carbon Fibre in Formula 1: The Material That Revolutionised Motorsport",
    tags: ["Technical", "Materials", "Carbon Fibre", "Safety"],
    imageUrl: IMGS.carbon,
    content: `Carbon fibre composite — a material that combines extremely thin carbon fibres woven into sheets and bonded with epoxy resin — has been the defining structural material of Formula 1 cars since McLaren pioneered the first carbon fibre monocoque in 1981. No other material comes close to its combination of stiffness, strength, and lightness that modern F1 car design demands.\n\nThe key property of carbon fibre composite is its **specific stiffness** — stiffness relative to weight. Pound for pound, carbon fibre is approximately five times stiffer than steel. An F1 car's survival cell — the central structural tub that the driver sits inside — can weigh as little as 35 kilograms while withstanding impacts of over 100G. The same structure in steel would weigh several hundred kilograms.\n\nF1 teams manufacture their own carbon fibre components in-house using **autoclave curing**: layers of pre-impregnated carbon fibre (prepreg) are laid up in precise orientations, bagged, and cured under heat and pressure to drive out air voids and set the resin. The fibre orientation is critical — fibres aligned along the primary load path provide maximum structural efficiency.\n\nThe aerodynamic components — wings, floor sections, bodywork — are optimised for aerodynamic performance first and structural performance second. A front wing endplate might be as thin as 0.5 millimetres. Yet it must withstand aerodynamic loads of hundreds of kilograms without deflecting measurably at speed — deflection would change the aerodynamic properties of the wing and potentially run foul of FIA legality tests.\n\nSafety is where carbon fibre's performance has been most visibly demonstrated. Romain Grosjean's 2020 Bahrain crash, in which his car split in two at roughly 220 km/h and burst into flames, was survived because the survival cell — doing exactly what it was designed to do — remained intact around the driver.`,
  },
  {
    keyword: "Suspension Setup",
    title: "F1 Suspension Setup: How Engineers Find the Perfect Balance",
    tags: ["Technical", "Suspension", "Engineering", "Setup"],
    imageUrl: IMGS.tech,
    content: `Formula 1 suspension setup is one of the most technically nuanced aspects of race weekend preparation. The suspension system connects the car's tyres to its chassis, and every adjustment made to it has cascading effects on aerodynamic performance, mechanical grip, tyre wear, and driver feel.\n\nModern F1 cars use **pushrod or pullrod suspension** at both ends of the car. In a pushrod system, a diagonal link running from the upright (which holds the wheel) pushes upward into the chassis, compressing a spring/damper unit inside the bodywork. Pullrod systems do the opposite — the link runs downward, pulling the suspension components. The choice between configurations affects packaging, centre of gravity, and the sensitivity of the suspension geometry to ride height changes.\n\n**Spring rates** determine how much the car resists vertical movement. A stiffer spring keeps the ride height more consistent — important for aerodynamic stability — but reduces the ability of the tyres to absorb bumps. Softer springs allow better mechanical grip over kerbs and uneven surfaces but can cause the car's aerodynamic platform to shift as it rolls or pitches.\n\n**Dampers** control how quickly the suspension moves through its travel. Bump damping resists compression (when the car hits a bump); rebound damping controls how quickly the suspension extends again. Getting the balance right between these two prevents the car from bouncing (too little damping) or refusing to settle over bumps (too much).\n\n**Anti-roll bars** connect the left and right suspension at each end of the car, resisting the body roll that occurs when the car corners. A stiffer front anti-roll bar transfers load to the outer front tyre in a corner, increasing understeer. A stiffer rear bar increases oversteer. The balance between front and rear anti-roll stiffness is one of the primary tools for adjusting the car's handling balance between circuits.`,
  },
  {
    keyword: "Brake System F1",
    title: "F1 Brakes Explained: How Cars Stop From 300 km/h in Under Two Seconds",
    tags: ["Technical", "Brakes", "Engineering", "Explainer"],
    imageUrl: IMGS.car,
    content: `The braking systems on a Formula 1 car are among the most extreme pieces of engineering on any racing machine. At maximum braking effort from 300 km/h, an F1 car can decelerate at over 5G — decelerating from motorway speeds to walking pace in roughly 65 metres. Understanding how this is achieved reveals the extraordinary precision at the cutting edge of motorsport engineering.\n\nF1 cars use **carbon-carbon brake discs and pads**. Unlike the cast iron discs on road cars, carbon-carbon composites operate most effectively at temperatures between 400°C and 1,000°C. Below this range — such as in the early laps of a race or after a safety car — the brakes are ineffective and drivers must manage their warming carefully. This is why you see F1 drivers weaving and braking hard on the formation lap.\n\n**Brake bias** — the proportion of braking force applied to the front versus rear — is adjustable from the steering wheel during the race. Moving bias forward increases stability under braking but risks front locking; moving it rearward can cause oversteer under trail braking. Drivers adjust brake bias at every corner that has specific braking characteristics requiring a different setup.\n\nThe **brake-by-wire** system on the rear axle, introduced with the hybrid regulations in 2014, electronically blends mechanical braking and regenerative braking from the MGU-K. The challenge is that the regenerative load changes as the battery state of charge varies — the system must make these adjustments completely transparently to the driver. Developing a brake-by-wire system that feels identical to a pure mechanical system across all conditions was one of the major engineering challenges of the hybrid era.\n\nBrake cooling is managed by ducting channels that direct airflow to the discs. The amount of cooling is circuit-specific: at Monza, with its long straights and heavy braking zones, maximum cooling is required. At Monaco, where speeds are lower, some teams reduce brake duct size for aerodynamic benefit.`,
  },
  {
    keyword: "F1 Gearbox",
    title: "The F1 Gearbox: Why a Gear Change Takes 15 Milliseconds",
    tags: ["Technical", "Gearbox", "Engineering", "Drivetrain"],
    imageUrl: IMGS.tech,
    content: `The Formula 1 gearbox is one of the most precisely engineered mechanical components in motorsport. Modern F1 transmissions shift gears in approximately 15 milliseconds — faster than the human eye can perceive — and must survive an entire season of grand prix racing while weighing less than a typical kitchen appliance.\n\nAll current F1 cars use a **semi-automatic sequential gearbox**. The driver operates paddle shifters mounted behind the steering wheel — typically the right paddle upshifts, the left downshifts — and electronics and hydraulics do the mechanical work. There is no clutch pedal; the clutch is operated automatically during gear changes and manually via a paddle only for race starts and pit lane entry.\n\nF1 gearboxes use **eight forward gears** (mandatory since 2014). The ratios are fixed for each car at the start of the season — teams must submit their gear ratio selection to the FIA and cannot change them without penalty. This means engineers must find a ratio spread that works across every circuit on the calendar: the same ratios that serve the car at Monza must also function at Monaco.\n\nThe gearbox casing is typically made from carbon fibre composite. Unlike the engine, which generates extreme temperatures and internal pressures, the gearbox operates in a lower thermal environment — but must handle the full engine torque multiplied by gear reduction, transmitted through a single small output shaft to the rear wheels.\n\nReliability regulations require the gearbox to last for six consecutive events. Teams managing grid penalties for gearbox changes must balance development updates against championship position — fitting a new component when a grid penalty has minimal championship impact. Managing this calendar across a 24-race season has become a significant element of strategic planning.`,
  },
  {
    keyword: "Halo Device",
    title: "The Halo: How F1's Most Controversial Safety Device Became Its Most Important",
    tags: ["Technical", "Safety", "Halo", "Engineering"],
    imageUrl: IMGS.cockpit,
    content: `No piece of safety equipment in Formula 1's recent history has saved more lives, and none was introduced to greater aesthetic objection. The halo — a titanium structure above the cockpit that protects the driver's head — was mandated by the FIA for the 2018 season following years of development and bitter controversy over its impact on visibility and the visual identity of the sport.\n\nThe halo is made from Grade 5 titanium — the same alloy used in aerospace applications for its exceptional strength-to-weight ratio. The structure weighs approximately 7 kilograms and can withstand a vertical static load of 125 kilonewtons — roughly equivalent to the weight of a London double-decker bus. Teams integrate it directly into the monocoque chassis structure; it is not a bolt-on addition.\n\nThe engineering case for the halo was supported by analysis of historical accidents where driver head protection would have altered outcomes. The FIA's simulations showed it would have protected Ayrton Senna at Imola in 1994. It would have deflected the wheel that struck Felipe Massa at the 2009 Hungarian Grand Prix.\n\nIn practice, its life-saving capability was demonstrated dramatically within three years of introduction. At the 2020 Bahrain Grand Prix, Romain Grosjean's car split in two at over 200 km/h and burst into flames. The halo diverted the main chassis barrier around the cockpit. Grosjean escaped with burns to his hands. At the 2021 British Grand Prix, Max Verstappen's Red Bull was struck on top by Lewis Hamilton's Mercedes at high speed — the halo bore the direct impact on the driver's helmet area.\n\nDriver opinion, initially hostile — Sebastian Vettel famously described it as the "worst aesthetic change" in F1 — shifted entirely after these incidents. Today it is universally accepted as non-negotiable.`,
  },
  {
    keyword: "Wind Tunnel Testing",
    title: "F1 Wind Tunnel Testing: How Aerodynamic Development Actually Works",
    tags: ["Technical", "Wind Tunnel", "Aerodynamics", "Development"],
    imageUrl: IMGS.tech,
    content: `Wind tunnel testing is the cornerstone of aerodynamic development for every Formula 1 team, despite the cost cap era introducing strict time limits on its use. Understanding how teams use this resource — and the constraints imposed on them — reveals much about how modern F1 cars are developed.\n\nFormula 1 wind tunnels are custom-built facilities costing hundreds of millions of pounds. The tunnels operate at a specific scale — typically 50% or 60% of the full car size — using a scaled model mounted on a moving belt that simulates the ground moving under the car as it would in real life. The moving belt is critical for accurate downforce and drag measurements because it eliminates the boundary layer that would otherwise form between the static floor and the model.\n\nThe FIA's **Aerodynamic Testing Restrictions (ATR)** limit the amount of wind tunnel time each team can use per year. The allocation is inversely proportional to championship position — teams that finished higher in the previous year's Constructors' Championship receive less wind tunnel and CFD time. This is a deliberate convergence mechanism: teams struggling with performance are given more development resource.\n\nThe correlation between wind tunnel results and track performance — whether the data gathered in the tunnel accurately predicts what the car will do at race speeds on real circuits — is one of the most significant technical challenges in the sport. Teams spend enormous effort on correlation work: comparing tunnel measurements with track sensors and CFD simulations to identify discrepancies and improve their model's accuracy.\n\n**Computational Fluid Dynamics (CFD)** runs in parallel with physical tunnel testing. CFD simulates airflow around virtual car models using supercomputer clusters, allowing teams to test thousands of geometrical changes per year that would be impossible to physically model. The FIA also limits CFD tokens — the computational resource each team can spend on aerodynamic simulations.`,
  },
  {
    keyword: "F1 Steering Wheel",
    title: "The F1 Steering Wheel: A Cockpit Control Centre With 25+ Buttons",
    tags: ["Technical", "Cockpit", "Technology", "Explainer"],
    imageUrl: IMGS.cockpit,
    content: `The steering wheel of a modern Formula 1 car is one of the most sophisticated pieces of driver interface technology ever created. Costing upwards of £50,000 to manufacture, it houses dozens of buttons, dials, and paddles that give the driver real-time control over hundreds of vehicle parameters while cornering at 5G and braking at 300 km/h.\n\nEach team designs their own steering wheel from scratch, tailored to the specific preferences of each driver. The core function — steering — accounts for a small fraction of what the wheel does. A typical modern F1 steering wheel includes: **gear shift paddles** (upshift right, downshift left), **clutch paddles** (for race starts), **brake bias adjustment** (a rotary dial), **DRS activation button**, **energy deployment mode selector**, **pit lane speed limiter**, **radio button**, **rev limiter override**, and various engine modes.\n\nThe **rotary dials** (sometimes 10 or more on a single wheel) control parameters like differential locking, traction control sensitivity (where permitted by regulations), fuel mixture, brake balance, and the engine's power unit deployment strategy. A driver must be able to locate and adjust these controls by touch at full racing speed — requiring hundreds of hours of ergonomic development.\n\nThe wheel's LCD display shows the driver critical real-time information: current gear, speed, lap time, tyre temperatures, fuel remaining, warning indicators, and engineer messages. Some teams display live rival gap information, pit strategy cues, and corner-specific setup reminders.\n\nThe evolution of the F1 steering wheel mirrors the evolution of the sport's complexity. In the 1980s, an F1 wheel had a gear lever and one or two buttons. The shift to semi-automatic gearboxes in 1989 began moving controls to the wheel. The hybrid era from 2014 onwards dramatically accelerated the wheel's complexity as energy deployment became a lap-by-lap driver management task.`,
  },
  {
    keyword: "Data Analytics F1",
    title: "How F1 Teams Use Data Analytics: 300 Sensors, 3GB Per Lap",
    tags: ["Technical", "Data", "Analytics", "Technology"],
    imageUrl: IMGS.data,
    content: `A modern Formula 1 car generates approximately 3 gigabytes of data per lap. With over 300 sensors monitoring everything from brake disc temperature and tyre pressure to suspension load and power unit efficiency, the challenge for teams is not collecting data — it is making sense of it fast enough to improve performance during a race weekend that lasts just three days.\n\nSensors are distributed across every critical system on the car. Tyre sensors monitor temperature and pressure at multiple points inside each tyre simultaneously. Suspension sensors measure the load, travel, and velocity of each corner's suspension in real time. Engine sensors track intake pressure, exhaust temperature, oil pressure, coolant flow, and the efficiency of every combustion cycle. Aerodynamic sensors measure the actual pressure distribution across wing surfaces.\n\nThis data is transmitted wirelessly from the car to the pit wall in real time, where it is processed by the team's data engineers and compared against the predictive models built before the session. Deviations from predicted values trigger investigation: if a tyre is running hotter than expected, is it because of a setup choice, a driving style issue, or a product anomaly from Pirelli? Finding the answer quickly — and communicating it to the driver with an actionable solution — is what separates teams.\n\nData engineers have become one of the most sought-after roles in the F1 paddock. The skills required — applied statistics, machine learning, systems engineering, and the ability to communicate complex findings to both engineers and drivers under pressure — are rare and increasingly valuable outside motorsport too.\n\nHistorical data compounds in value over time. A team that has raced at a circuit for 20 years has millions of data points from previous visits — tyre wear curves, weather correlations, safety car probability models — that a new or struggling team simply cannot replicate. This data heritage is a genuine competitive advantage.`,
  },
  {
    keyword: "Active Suspension History",
    title: "Active Suspension: The Technology That Made F1 Cars Almost Too Fast",
    tags: ["Technical", "Suspension", "F1 History", "Technology"],
    imageUrl: IMGS.car,
    content: `Between 1987 and 1993, a handful of Formula 1 teams developed and deployed active suspension systems that transformed the performance ceiling of the sport — and raised enough safety concerns about technological complexity that the FIA banned them entirely for 1994. The story of active suspension remains one of the most fascinating technical chapters in F1 history.\n\nConventional passive suspension uses springs and dampers to absorb road irregularities. Active suspension replaces these with hydraulic actuators controlled by a computer. The system continuously monitors the car's motion — ride height, pitch, roll, vertical acceleration — and adjusts the suspension position at each corner to maintain optimal aerodynamic platform regardless of what the car is doing.\n\nThe aerodynamic benefit was enormous. An F1 car's downforce is highly sensitive to its ride height — the gap between the floor of the car and the track surface. Passive suspension allows the car to pitch and roll as it brakes, corners, and accelerates, causing the ride height to change continuously. Active suspension eliminated this variation, keeping the car at its ideal aerodynamic height throughout the lap.\n\nWilliams were the dominant force in active suspension development. Their FW14B of 1992 — driven by Nigel Mansell to nine wins from 16 races — is widely regarded as one of the most technically superior cars ever built. The active suspension allowed Mansell to corner at speeds that were simply unachievable for teams on passive suspension.\n\nThe FIA's decision to ban active suspension for 1994 was part of a broader effort to reduce the performance gap between well-funded and less well-funded teams, and to ensure that driving skill rather than electronics determined outcomes. Whether that goal was achieved — or whether the subsequent accident fatalities of 1994 were connected to the loss of stability aids — remains debated.`,
  },
  {
    keyword: "ERS Deployment",
    title: "ERS Deployment Strategy: How F1 Drivers Use Electrical Power to Attack and Defend",
    tags: ["Technical", "ERS", "Hybrid", "Strategy"],
    imageUrl: IMGS.speed,
    content: `The Energy Recovery System (ERS) in a modern Formula 1 car is not just a fuel-saving technology — it is an active performance weapon that skilled drivers deploy tactically throughout a lap and across a race. Understanding how ERS deployment works reveals a hidden layer of strategy invisible to television viewers but critical to race outcomes.\n\nThe ERS consists of the Motor Generator Unit-Kinetic (MGU-K), which recovers energy under braking and deploys it during acceleration, and the battery (Energy Store) that manages the electrical charge. Under the 2014-2025 regulations, the MGU-K could deploy a maximum of 120kW (about 161 horsepower) per lap cycle. The 2026 regulations removed this cap, allowing significantly more electrical deployment.\n\nThe key tactical use of ERS is **temporal deployment** — choosing when within a lap to release stored electrical energy. In a standard lap, ERS recharges under braking and deploys on exit from slow corners and on straights. But the amounts and timings can be varied: saving deployment through one section to have an advantage in another, or deploying extra charge into a heavy braking zone to have electrical boost available on a following straight where an overtake is possible.\n\n**Defending with ERS** is equally important. A driver being chased by a faster car can deploy additional electrical energy on the approach to a DRS detection point, extending the gap beyond one second and preventing DRS activation. A driver running low on battery charge is vulnerable to attack in specific sections of the lap — experienced teams track rival ERS state through telemetry analysis and timing data.\n\nThe management of the ERS across a race distance — ensuring sufficient charge is available when needed most, without compromising battery health or exceeding deployment allowances — is an ongoing communication between driver and engineer throughout the race.`,
  },
  {
    keyword: "Safety Car Rules",
    title: "Safety Car and Virtual Safety Car: The Rules That Can Swing a Championship",
    tags: ["Regulations", "Safety Car", "Strategy", "Explainer"],
    imageUrl: IMGS.track,
    content: `The safety car and virtual safety car are among the most strategically significant interventions in a Formula 1 race. Understanding the precise regulations governing their deployment — and the strategic responses they trigger — is essential to reading a grand prix intelligently.\n\nThe **safety car** is deployed when an incident creates conditions the race director deems too dangerous for racing. All cars must reduce speed and form a queue behind the safety car within a specified time. Overtaking is prohibited except in specific circumstances. Critically: pit stops can be taken during a safety car period with minimal time loss because the gaps between cars close as the field bunches up.\n\nThe strategic opportunity created by an unexpected safety car is substantial. A team whose car is running on worn tyres can pit with minimal loss of position — the cars behind are also slowing, so the time lost on the out-lap is reduced. Conversely, a team that has just pitted finds their fresh-tyre advantage wiped out as rivals are allowed to pit for free.\n\nThe **virtual safety car (VSC)**, introduced in 2015, neutralises the race without physically deploying the safety car. Drivers must maintain a minimum lap time (roughly 30-40% slower than racing pace) rather than following a physical car. The VSC creates its own strategic opportunities: pit stops can be taken with less time loss than normal racing conditions, though more time loss than under a full safety car.\n\nThe 2021 Abu Dhabi Grand Prix finale — where the decision to allow five lapped cars (but not all lapped cars) to overtake the safety car before the final lap restart — set up the championship-deciding battle between Lewis Hamilton and Max Verstappen. The subsequent FIA investigation resulted in the introduction of updated safety car procedures and a clarification that, under the sporting regulations, the race director's decisions on safety car deployment could not be overridden.`,
  },
  {
    keyword: "Qualifying Format",
    title: "How F1 Qualifying Works: Q1, Q2, Q3 and the Tyre Rule Explained",
    tags: ["Explainer", "Qualifying", "Format", "Strategy"],
    imageUrl: IMGS.track,
    content: `Formula 1 qualifying is a knockout format that determines the starting grid for Sunday's race. Spread across three sessions with eliminations, it creates a genuine contest for pole position that is often as exciting as the race itself. Understanding the format — and the tyre strategy implications — is key to following the full depth of a race weekend.\n\n**Q1** runs for 18 minutes with all 20 drivers. The five slowest — those in positions 16-20 at the chequered flag — are eliminated and locked into grid positions 16-20 for Sunday. **Q2** follows immediately with the remaining 15 cars and lasts 15 minutes. The five slowest are again eliminated, taking positions 11-15. **Q3** is the final 12-minute shootout among the top ten to determine the front of the grid.\n\nThe critical strategic layer is the **tyre rule**: any driver who progresses from Q2 must start Sunday's race on the same compound they used to set their fastest Q2 lap time. This creates a genuine dilemma. A driver on the Medium tyre in Q2 has a better race strategic position — they can run longer before pitting — but risks not making Q3 if the Medium doesn't provide enough pace to beat rivals on Softs. A driver on Softs secures Q3 progression more reliably but starts on a tyre that degrades faster, potentially requiring an earlier first pit stop.\n\nIn practice, Q3 drivers are usually free to use any tyre since their Q2 compound rule is already set. Teams will typically use a second set of Softs in Q3 for the fastest possible qualifying lap, saving a set of Mediums for race day. On a wet qualifying day, all bets are off: the rain interrupts tyre strategy and the grid can be scrambled entirely.\n\nSprint weekends use a modified format. A Sprint Shootout on Friday determines the grid for Saturday's Sprint race — run in three compressed sessions (SQ1, SQ2, SQ3). Standard qualifying then runs on Saturday afternoon for Sunday's race grid.`,
  },
  {
    keyword: "F1 Points System",
    title: "The F1 Points System: How 25 Points in Australia Can Win a Championship in Abu Dhabi",
    tags: ["Explainer", "Points", "Championship", "Regulations"],
    imageUrl: IMGS.circuit,
    content: `The Formula 1 World Championship is decided by a points system that converts individual race results into a season-long hierarchy. The current system — 25 points for the winner, descending to 1 point for tenth — has been in use since 2010 and has profoundly shaped how teams and drivers approach strategic decisions across the season.\n\nThe full current allocation is: 1st-25, 2nd-18, 3rd-15, 4th-12, 5th-10, 6th-8, 7th-6, 8th-4, 9th-2, 10th-1. An additional **1 point is awarded for the fastest lap** in the race, but only to a driver finishing in the points (top 10). This bonus point was introduced in 2019 and has occasionally been tactically significant — teams sending drivers to pit for fresh tyres late in a race specifically to target it.\n\nOn **Sprint weekends**, an additional smaller points allocation is awarded for the top eight Sprint race finishers: 8, 7, 6, 5, 4, 3, 2, 1. These points count toward both the Drivers' and Constructors' Championships and have occasionally influenced the championship standings materially when margins were tight.\n\nThe gap between first and second place — 7 points — is large enough that consistent podium finishes will outscore a driver who wins half the races but retires from others. This built-in premium on reliability has historically made race-finishing consistency as important as outright pace in championship mathematics. Red Bull's 2023 dominance, for example, was partly a reflection of Max Verstappen's extraordinary win rate and partly a reflection of their exceptional reliability across the season.\n\nThe Constructors' Championship awards the same points to the team from both their drivers' finishes combined. This creates internal team dynamics around which driver's car gets priority for setup updates, and occasionally triggers explicit team orders to maximise constructors points.`,
  },
  {
    keyword: "Monaco Grand Prix",
    title: "Monaco: Why the Slowest Race on the Calendar Is the Most Prestigious",
    tags: ["Circuits", "Monaco", "F1 History", "Street Circuit"],
    imageUrl: IMGS.circuit,
    content: `Monaco is a paradox. The slowest circuit on the Formula 1 calendar — its layout allows average speeds that would be unimpressive at most other venues — attracts the most intense desire to win of any race in the sport. To win at Monaco is to join a pantheon that includes Senna, Stewart, Prost, and Hill. It is the one grand prix every driver prioritises above all others.\n\nThe circuit's character stems entirely from its geography. The streets of the Principality of Monaco were never designed for motor racing. The barriers are so close to the car that drivers regularly touch armco on flying laps. There is effectively zero run-off. A mistake does not result in a trip across a gravel bed and a slow return to the track — it results in immediate terminal contact with a wall at whatever speed the error was made.\n\nThis unforgiving nature elevates qualifying to an almost mythological status at Monaco. Overtaking during the race is essentially impossible due to the circuit's narrow passages and lack of long straights. Grid position is therefore everything — the driver who qualifies on pole has an overwhelming statistical advantage to win. This is why Monaco qualifying generates some of the most spectacular single-lap performances in the sport.\n\nThe circuit's layout has barely changed since the 1970s. While other street circuits — Baku, Las Vegas, Singapore, Jeddah — have been added to the calendar with wider roads and more overtaking opportunities, Monaco remains stubbornly itself. Its casino corner, tunnel exit, swimming pool complex, and Rascasse corner are part of F1's visual vocabulary.\n\nAyrton Senna won Monaco six times — a record that may never be broken. His 1984 drive through the field in a midfield Toleman before the race was red-flagged in controversial circumstances, and his 1992 wheel-to-wheel battle with Nigel Mansell in the closing laps, remain among the most replayed moments in the sport's history.`,
  },
  {
    keyword: "F1 Budget Cap",
    title: "The F1 Cost Cap Explained: How $135 Million Reshaped the Competitive Order",
    tags: ["Regulations", "Budget Cap", "Business of F1"],
    imageUrl: IMGS.data,
    content: `Formula 1's financial cost cap, introduced for the 2021 season, is the most significant structural reform to the sport's competitive framework in its history. Before 2021, the teams with the deepest pockets could simply outspend rivals into submission. The cost cap changed the equation — and its impact on the competitive order has been more immediate than many expected.\n\nThe cap applies to what the FIA defines as "performance-related expenditure" — essentially everything directly connected to designing, building, and operating the racing car. For 2024, the cap stood at $135 million for a 23-race season, with additional allowances for extra races beyond 21. Large portions of team spending are excluded: driver salaries above a threshold, the three highest-paid staff members at each team, marketing and hospitality costs, and the CEO's salary.\n\nCompliance is monitored through rigorous financial reporting. Teams submit detailed audited accounts to the FIA's Cost Cap Administration. The FIA employs dedicated financial scrutineers who assess the submissions and can request detailed supporting evidence for any line item. Teams are permitted to use transfer pricing rules for goods and services exchanged within the same corporate group — a complexity that has been a source of ongoing interpretation.\n\nThe first major enforcement test came in late 2022 when the FIA found Red Bull Racing to have exceeded the 2021 cap by a relatively modest amount — around $1.8 million, approximately 1.3% over the limit. The resulting penalty — a $7 million fine and a 10% reduction in aerodynamic testing time for the following year — was considered by many in the sport to be insufficiently deterrent for the benefit potentially gained.\n\nThe cap's impact on the midfield has been transformative. Teams previously operating on budgets well below the cap — teams like Alpine, McLaren before their 2019-era investment — found the cap represented an increase in their available resources. The competitive bunching visible across F1 grids since 2021 is widely attributed, at least in part, to this equalisation effect.`,
  },
  {
    keyword: "F1 Fastest Laps",
    title: "Speed Records in F1: The Fastest Laps, Top Speeds and Records That Defined Eras",
    tags: ["Records", "Speed", "F1 History", "Technical"],
    imageUrl: IMGS.speed,
    content: `Speed is Formula 1's defining characteristic, and the lap records set at each circuit on the calendar represent the absolute limit of what human beings and machines can achieve together. Comparing these records across eras tells the story of the sport's extraordinary technical progression — and its occasional regressions in the name of safety.\n\nThe fastest cars in Formula 1 history, in terms of single-lap speed, were the qualifying cars of the 1980s turbo era. Running on special fuels with turbocharger boost pressure far beyond their race settings, these cars — led by the BMW-powered Brabham and the Renault-powered Williams — are estimated to have produced over 1,400 horsepower from 1.5-litre engines. The lap records they set at circuits in the original 1980s configurations have never been approached.\n\nAt circuits unchanged since the turbo era — Monza, in its modern configuration — lap records tell a different story. The current fastest Monza race lap was set in 2019 by Charles Leclerc's Ferrari, at an average of approximately 263 km/h. The top speed measured on the main straight approaches 375 km/h during qualifying at low-downforce specification.\n\nThe **fastest lap bonus point**, reintroduced in 2019, added a tactical dimension to race lap records. Teams now routinely pit a driver for fresh tyres in the final laps specifically to target the fastest lap. At circuits where the fastest lap point could be decisive in the championship, this tactic has occasionally influenced pit stop decisions that change race outcomes.\n\nIn terms of outright top speed, Formula 1's fastest recorded speed on a public circuit is roughly 375 km/h at Monza and approximately 378 km/h at the 2016 Mexican Grand Prix, where the high altitude reduces air resistance significantly. The theoretical maximum speed achievable by a 2026-specification car in minimum-downforce trim is estimated to exceed 400 km/h.`,
  },
  {
    keyword: "F1 Teams History",
    title: "F1 Team History: Why Only Ferrari Have Been There From the Beginning",
    tags: ["F1 History", "Teams", "Paddock", "Ferrari"],
    imageUrl: IMGS.track,
    content: `More than one hundred constructors have contested the Formula 1 World Championship since it began in 1950. Of those, ten remain today. The story of which teams survived — and which did not — reveals the sport's brutal economics and the small margins that separate legendary teams from forgotten ones.\n\nOnly **Ferrari** has competed in every season of the World Championship without exception. The Scuderia's presence is so fundamental to Formula 1's commercial identity that they receive a unique annual payment — the "historic payment" — simply for being part of the sport. Every other team's continued existence depends on competitiveness and commercial success. Ferrari's does not, at least partially.\n\n**McLaren** entered F1 in 1966, founded by New Zealand driver Bruce McLaren who died testing a Can-Am car at Goodwood in 1970. The team he created survived, and went on to win 183 races — second only to Ferrari in the all-time list. Their 1988 season remains the benchmark of dominance: 15 wins from 16 races with Ayrton Senna and Alain Prost.\n\n**Williams** — founded by Frank Williams and Patrick Head in 1977 — built a record of 16 Constructors' Championships across the 1980s and 1990s before declining sharply in the 2000s as the budgets required for competitiveness outgrew their commercial base. Sold to a US investment group in 2020, the team continues under new ownership.\n\nThe failures are equally instructive. **Brabham** (two Constructors' Championships), **Tyrrell** (1971 champion with Jackie Stewart), **Lotus** (seven Constructors' titles), **Ligier**, **Jordan** — all are gone. The most recent departures — HRT, Caterham, and Marussia, who all entered the sport during the 2010 expansion — failed within five years of their debut. Building a competitive F1 team requires hundreds of millions of pounds annually, and the point at which costs exceed commercial returns arrives for most teams eventually.`,
  },
  {
    keyword: "F1 Wet Weather",
    title: "Wet Weather Driving in F1: Why Rain Separates Champions from Contenders",
    tags: ["Technique", "Wet Weather", "Driver Skills", "Racing"],
    imageUrl: IMGS.track,
    content: `Wet weather driving in Formula 1 is widely regarded as the purest test of driving talent in the sport. When grip levels drop dramatically, aerodynamic downforce becomes less relevant, and raw feel for the car — the ability to sense the limit of adhesion through fingertips, seat, and pedals — becomes the overwhelming differentiator. The drivers who shine in the rain are often the same drivers considered the greatest of their generation.\n\nThe primary tool in wet weather is the **Intermediate tyre** or the **Full Wet tyre**. Intermediates are designed for damp but not fully saturated conditions — their compound generates heat faster than Full Wets and their tread channels evacuate water without the performance loss of a fully grooved tyre. Full Wets evacuate up to 65 litres of water per second from their contact patch and are used in the heaviest standing water conditions. Choosing when to switch between them — and timing the switch correctly — is one of the most significant calls in a wet race.\n\nThe racing line in the wet is frequently different from the dry line. The rubber deposited by thousands of laps of dry running becomes a polished, slippery surface when wet. The cleanest and most effective grip is often found off the usual racing line, on the unprepared road surface that retains more texture. Drivers who remain on the standard dry racing line in the early laps of a wet race often struggle while those willing to venture off-line find more traction.\n\nAyrton Senna was universally regarded as the finest wet weather driver of his era — his pole position at the 1984 Monaco Grand Prix in an uncompetitive Toleman, and his dominant 1993 European Grand Prix victory at Donington Park, are the canonical examples. Michael Schumacher, Lewis Hamilton, and Max Verstappen have all produced iconic wet weather performances that reinforced their status as generational talents.`,
  },
  {
    keyword: "F1 Tyre Management",
    title: "Tyre Management in F1: How Drivers Look After Their Most Critical Asset",
    tags: ["Technical", "Tyres", "Strategy", "Driver Skills"],
    imageUrl: IMGS.tyre,
    content: `Tyre management — the art of extracting maximum performance from a set of Pirelli compounds while simultaneously ensuring they do not degrade before the planned pit stop — is one of the most complex skills in Formula 1. It is invisible to television viewers, but often the primary determinant of race results.\n\nThe core challenge is thermal: every tyre compound operates within a specific temperature window where its rubber is at peak performance. Above this window the rubber blisters, generates excessive wear, and eventually "falls off the cliff" — losing grip dramatically in the space of one or two laps. Below the window the compound is too cold and provides insufficient mechanical grip. Keeping four tyres at four different positions simultaneously within their optimal windows, while also extracting maximum lap time, is the essence of the skill.\n\n**Sliding** is the primary enemy of tyre life. When a tyre slides — whether from understeer (the front not following the steering input), oversteer (the rear stepping out), or wheelspin — the rubber scrubs against the track surface and generates excess heat. A driver who can minimise sliding by using perfectly smooth inputs — gentle steering, progressive throttle, measured brake release — will typically extend their tyre life dramatically compared to a driver with more aggressive technique.\n\n**Tyre saving laps** are common in the middle stint of a race. When strategy demands a long final stint on a harder compound, the engineer will sometimes ask the driver to "take care" of the tyres for a defined period — deliberately lapping at a controlled pace to keep temperatures down before the critical closing laps when maximum performance is needed.\n\nThe difference in tyre management capability between teammates on identical equipment is one of the clearest comparative metrics in F1. Teams use it to evaluate driver performance and to identify setup changes that help the more managing driver's technique.`,
  },
  {
    keyword: "F1 Race Start",
    title: "The F1 Race Start: Why the First Corner Decides More Races Than Any Other",
    tags: ["Technique", "Race Start", "Strategy", "Driver Skills"],
    imageUrl: IMGS.car,
    content: `The Formula 1 race start is the most compressed moment of strategic and physical intensity in the sport. In the four to five seconds between lights out and the first braking point, positions are gained and lost that can determine the entire shape of a grand prix. Understanding what determines a good start — and why they are so difficult to execute consistently — reveals the extraordinary demands of F1 driving.\n\nThe modern F1 start procedure requires the driver to manage three simultaneous variables: clutch engagement, throttle position, and wheelspin. At the moment the lights go out, the driver must release the clutch from its pre-set launch position while progressively increasing throttle input, monitoring whether the tyres are spinning (too much wheelspin wastes drive) or gripping (too little throttle means a slow launch).\n\nThe **launch control systems** that many fans assume modern F1 cars use have been banned since 2008. All starts must be managed manually by the driver. However, the cars do have systems that can **limit wheelspin** to a degree — the engine management software prevents catastrophic spinning that would cause the driver to go nowhere. The fine-tuning above this basic limit is the driver's responsibility.\n\nReaction time to the lights is less important than many assume. An experienced driver cannot consciously see the lights go out and react within a few hundred milliseconds — the response is trained as a near-reflex. What matters more is the **consistency** of that reflex under the pressure of 300,000 spectators and live global television.\n\nThe **first corner** is where the start's consequences are decided. Even a driver who launches well can lose multiple positions if they brake too early at the first braking zone. The mathematics of closing speed — a car that has made two positions on the straight arriving two car lengths faster into the corner — require precise judgement of how late to brake while avoiding contact with cars defending their positions.`,
  },
  {
    keyword: "Pit Stop F1",
    title: "The F1 Pit Stop: How 22 People Change Four Tyres in Under 2 Seconds",
    tags: ["Technical", "Pit Stop", "Team", "Operations"],
    imageUrl: IMGS.pit,
    content: `The modern Formula 1 pit stop is one of the most finely choreographed physical operations in professional sport. The world record for a four-tyre change, set by Red Bull Racing in 2023, stands at 1.80 seconds. Understanding how this is achieved — and why a poor stop can cost a driver a race win — reveals the extraordinary operational precision required at the front of the grid.\n\nA modern pit stop involves **22 people working simultaneously**. Each of the four wheel stations has a nut gun operator (who removes and fastens the single central wheel nut), a new tyre carrier (who brings the fresh tyre from storage and positions it on the hub), and a tyre holder (who steadies the tyre during fitting). Additional team members operate the front and rear jacks, two brake duct adjusters, two front wing adjusters, and a lollipop or traffic light operator who signals the release.\n\nThe **single central wheel nut** is one of F1's most critical single components. Unlike road cars with five-bolt wheels, F1 uses a single large nut threaded in the opposite direction on left-side and right-side wheels — so that forward rotation of the nut gun tightens rather than loosens it during racing. The nut must be torqued to specification precisely; an undertightened nut can cause a wheel to detach at high speed, as has happened multiple times in F1 history.\n\nPit stop training is taken extraordinarily seriously. Teams run timed practice sessions dozens of times per week between grands prix, conditioning the muscle memory and inter-team coordination that allows 22 people to execute a process of incredible precision in under two seconds consistently. The **wheel gun operators** — perhaps the most critical role — practise individual nut engagement thousands of times.\n\nThe strategic timing of pit stops — the lap on which to bring the car in — is calculated by the strategist based on tyre degradation model, rival team strategies, and the track position implications. Getting the timing right can neutralise a rival's advantage or capitalise on a gap in traffic.`,
  },
  {
    keyword: "F1 Car Weight",
    title: "Why F1 Cars Keep Getting Heavier — And Why It Actually Matters",
    tags: ["Technical", "Regulations", "Car Design", "Weight"],
    imageUrl: IMGS.car,
    content: `In 1950, a Formula 1 car weighed approximately 700 kilograms. Today, the minimum weight limit stands at 798 kilograms including the driver. This near-doubling over 75 years might seem contradictory for a sport defined by lightness and performance — but the reasons behind the increase reveal how profoundly the sport's priorities have evolved.\n\nThe primary driver of increasing weight is **safety**. The carbon fibre survival cell protecting the driver weighs less than 40 kilograms but must pass the FIA's mandatory crash tests. The halo adds 7 kilograms. Mandatory side impact structures, fire suppression systems, the fuel cell, the roll hoop, the head restraint (HANS device), and numerous sensors add weight that simply did not exist in the sport's early decades.\n\nHybrid power units are the other major factor. The battery system, motor generator units, and their associated cooling infrastructure add 30-50 kilograms compared to a pure combustion engine of equivalent displacement. The performance benefit — over 400kW of combined output — compensates for this mass penalty in terms of outright speed, but the weight is unavoidable.\n\n**Wheel size** contributed to a step change in 2022. The move from 13-inch to 18-inch wheel rims brought heavier tyres and rims, contributing to an increase in the minimum weight limit that cycle. The 18-inch format was driven by road car relevance — modern premium road cars all use large-diameter low-profile tyres, and Pirelli's partnership with F1 justifies investment in 18-inch tyre development.\n\nFor drivers, the weight regulations create an unusual dynamic. Lighter drivers have historically carried ballast to reach the minimum weight limit, which they can place strategically for ideal weight distribution — a performance benefit. Taller, heavier drivers have less flexibility with ballast placement. The 2023 regulations introduced a minimum driver weight of 80 kilograms (including seat) specifically to reduce the extreme weight management practices some lighter drivers previously adopted.`,
  },
  {
    keyword: "F1 Driver Training",
    title: "How F1 Drivers Train: The Physical and Mental Demands of Racing at the Limit",
    tags: ["Drivers", "Training", "Physical", "Mental"],
    imageUrl: IMGS.helmet,
    content: `Formula 1 drivers endure physical forces during a race that would be incapacitating for most people. Understanding the specific demands imposed by modern F1 cars — and how drivers train to meet them — reveals an athletic discipline that is consistently underestimated.\n\nThe primary physical challenge is **neck strength**. Under cornering loads of up to 6G, the head and helmet — together weighing approximately 7 kilograms — exert a force equivalent to 42 kilograms on the driver's neck. A typical grand prix features over 50 high-speed corners, and the cumulative neck loading across a 90-minute race is substantial. F1 drivers train neck-specific resistance exercises year-round and maintain neck circumferences of 40+ centimetres.\n\n**Cardiovascular fitness** is required because the cockpit of an F1 car reaches ambient temperatures of 50-55°C during a race, while the driver wears a multi-layer fireproof suit. Heart rates regularly reach 180-190 BPM during intense phases of racing — comparable to a professional cyclist at full effort — and must be sustained for the race duration. Sweat loss can exceed 2-3 kilograms per race.\n\n**Core and grip strength** are necessary to hold the steering wheel against the aerodynamic forces pushing it off-centre and to maintain a stable position in the cockpit under braking loads. Drivers maintain their core with the same rigour as professional gymnasts or martial artists.\n\nThe **mental demands** are equally intensive. A driver must process tyre condition, fuel load, rival positions, engineer instructions, braking points, and the constantly changing behaviour of the car — simultaneously, at 300 km/h, for 90 minutes. The reaction time requirements for avoiding incidents are measured in tens of milliseconds. Developing and maintaining this level of attentional processing is a full-time cognitive training effort distinct from the physical programme.`,
  },
  {
    keyword: "F1 Radio Communications",
    title: "F1 Team Radio: How Engineers and Drivers Communicate at 300 km/h",
    tags: ["Technical", "Communication", "Strategy", "Driver Skills"],
    imageUrl: IMGS.cockpit,
    content: `Formula 1 team radio communications are a window into the real-time decision-making of the sport's most technically demanding discipline. The brief exchanges heard on television broadcasts — clipped, coded, sometimes emotional — represent a tiny fraction of the constant two-way information flow between driver and race engineer across a typical grand prix weekend.\n\nThe race engineer is the driver's primary contact at the pit wall. Their role combines data analysis, tyre and fuel management, strategy execution, and psychological support into a single demanding position. A skilled race engineer delivers critical information at precisely the right moment — neither so early that the driver forgets it, nor so late that it cannot be acted upon — while keeping the communication brief enough to avoid overloading the driver during high-intensity laps.\n\nCertain message types are prohibited under the FIA's regulations. Teams cannot transmit **"real-time driver coaching"** — specific information that helps a driver modify their technique in a corner, such as "you're braking three metres too early at Turn 7." This rule, introduced progressively from 2016 onwards, was intended to ensure that the driver's skill — rather than the engineer's technical feedback — was the primary performance differentiator. In practice, the boundary between permitted tactical information and prohibited coaching is regularly tested.\n\n**Code words** are standard across the paddock. Teams develop their own vocabulary for competitor positions, tyre status, strategy changes, and mechanical concerns — partly to communicate efficiently and partly to prevent rivals from decoding sensitive information from the broadcast feeds. When a driver is told to "pick up the pace — the window is closing," the message carries a precise strategic meaning that only driver, engineer, and analyst fully understand in context.\n\nThe emotional dimension of team radio is occasionally revealed by the cameras: celebrations, frustrations, disagreements, and reassurances all happen through the same communication channel used to relay brake bias adjustments and lap time data.`,
  },
  {
    keyword: "F1 Circuit Design",
    title: "How F1 Circuits Are Designed: The Science Behind the World's Greatest Tracks",
    tags: ["Circuits", "Design", "Technical", "FIA"],
    imageUrl: IMGS.circuit,
    content: `Every Formula 1 circuit is a compromise between competing demands: the requirements of wheel-to-wheel racing, safety standards, commercial viability, urban geography, and the aesthetic ambitions of the designers who shaped them. Understanding how circuits are designed — and what separates a great racing track from an ordinary one — reveals why some venues produce memorable races year after year and others do not.\n\nThe FIA's **Grade 1 circuit licence** is required for an F1 venue. The criteria cover run-off areas, barrier standards, medical facility specifications, marshal post positions, circuit width minimums, and numerous other safety metrics. Meeting Grade 1 standards at a street circuit — where the infrastructure must be temporarily installed and removed each year — is significantly more complex and expensive than at a permanent facility.\n\n**Overtaking zones** are central to circuit design philosophy. The best F1 tracks — Spa, Bahrain, Austin, Monza — provide multiple distinct heavy braking zones where a faster car can attack the one ahead on a different line. Poor overtaking venues (Monaco, Hungary, Singapore) share a common characteristic: narrow roads, few genuine braking zones, and the inability of a car on the inside to have a different entry speed to the car defending the outside.\n\n**Track surface texture** significantly affects tyre performance and degradation. Teams spend time before each event analysing surface maps — the micro-texture, macrotexture, and surface roughness that determine how aggressively the tyre compound wears. New asphalt is typically very smooth and low-grip initially, evolving over the course of a race weekend as rubber is laid down by the cars.\n\nThe **tilke era** of circuit design — beginning with the 2002 Malaysian Grand Prix at Sepang, designed by German architect Hermann Tilke — introduced a consistent aesthetic: wide main straights for overtaking, tight first corners to compress the field, varied medium-speed corner sequences, and generous run-off. Critics have argued that Tilke circuits, despite their safety credentials, often produce predictable racing.`,
  },
];

export async function generateAndPublishBatch(count: number = MAX_PER_DAY): Promise<{
  success: boolean;
  submitted: string[];
  skipped: number;
  noContent: boolean;
  message?: string;
}> {
  try {
    const today = new Date();
    const todayStr = today.toISOString().split("T")[0];

    const [published, pending] = await Promise.all([
      storage.getArticles(),
      storage.getPendingArticles(),
    ]);
    const allArticles = [...published, ...pending];

    // Count how many auto-articles already submitted today
    const todayAutoArticles = allArticles.filter((a: any) => {
      const dateField = a.publishedAt || a.createdAt;
      const date = dateField ? new Date(dateField).toISOString().split("T")[0] : "";
      return date === todayStr && a.authorId === ADMIN_ID;
    });

    const remaining = count - todayAutoArticles.length;
    if (remaining <= 0) {
      return {
        success: false,
        submitted: [],
        skipped: 0,
        noContent: false,
        message: `Already auto-submitted ${todayAutoArticles.length} article(s) today. Come back tomorrow.`,
      };
    }

    // Build recent auto-article titles for deduplication (last 90 days)
    const cutoff = new Date(today.getTime() - 90 * 24 * 60 * 60 * 1000);
    const recentAutoTitles = allArticles
      .filter((a: any) => {
        if (a.authorId !== ADMIN_ID) return false;
        const dateField = a.publishedAt || a.createdAt;
        return dateField ? new Date(dateField) > cutoff : false;
      })
      .map((a: any) => a.title as string);

    // Load live data
    const [races, drivers, constructors] = await Promise.all([
      storage.getAllRaces(2026),
      storage.getDriverStandings(2026),
      storage.getConstructorStandings(2026),
    ]);

    const nowMs = today.getTime();
    const upcoming = races
      .filter((r) => r.status === "upcoming" || r.status === "live")
      .sort((a, b) => new Date(a.raceDate).getTime() - new Date(b.raceDate).getTime());
    const completed = races
      .filter((r) => r.status === "completed")
      .sort((a, b) => new Date(b.raceDate).getTime() - new Date(a.raceDate).getTime());

    const nextRace = upcoming[0];
    const lastRace = completed[0];
    const top3Drivers = drivers.slice(0, 3);
    const top2Constructors = constructors.slice(0, 2);

    // Collect all candidate articles in priority order
    type Candidate = { title: string; excerpt: string; content: string; tags: string[]; imageUrl: string | null; sortOrder: number };
    const candidates: Candidate[] = [];

    // Race preview
    if (nextRace) {
      const daysUntil = Math.ceil((new Date(nextRace.raceDate).getTime() - nowMs) / (1000 * 60 * 60 * 24));
      if (daysUntil >= 0 && daysUntil <= 7 && !alreadyCovered(recentAutoTitles, nextRace.name + " Preview")) {
        const leader = top3Drivers[0];
        const second = top3Drivers[1];
        const ptsDiff = leader && second ? leader.points - second.points : 0;
        const topConstructor = top2Constructors[0];
        candidates.push({
          title: `${nextRace.name} Preview: Everything to Know Ahead of Round ${nextRace.round}`,
          excerpt: `Formula 1 heads to ${nextRace.location}, ${nextRace.country} for the ${nextRace.name}. Here is everything you need to know heading into what promises to be a critical round.`,
          imageUrl: IMGS.circuit,
          tags: [nextRace.country, "Race Preview", "2026 Season", nextRace.name],
          sortOrder: 1,
          content: `Formula 1 returns to ${nextRace.circuit} in ${nextRace.location}, ${nextRace.country} for the ${nextRace.name} — Round ${ordinal(nextRace.round)} of the 2026 World Championship.${nextRace.hasSprint ? " This is a Sprint weekend, with additional championship points on offer from Saturday's Sprint race." : ""}\n\n## Championship Situation\n\n${leader && second ? `${leader.driverName} leads the Drivers' Championship with ${leader.points} points, ${ptsDiff} ahead of ${second.driverName}.` : ""} ${topConstructor ? `${topConstructor.teamName} lead the Constructors' standings.` : ""} With ${upcoming.length} rounds remaining, every point has championship significance.\n\n## Circuit Profile: ${nextRace.circuit}\n\n${nextRace.circuit} demands a precise setup balance between downforce for its technical corners and aerodynamic efficiency on the straights. Tyre management will be critical — the compound selection and thermal characteristics of this venue place a specific premium on smooth driving.\n\n## Key Questions\n\nWhich team has found the better setup direction? Can the championship leader hold their advantage under pressure from a charging rival? Will track characteristics favour any specific team concept and upset the established order?\n\n${nextRace.raceDate ? `The race starts on ${formatDate(nextRace.raceDate)}.` : ""} Full analysis, qualifying reaction, and race reports will be available here on F1 Fan Hub throughout the weekend.`,
        });
      }
    }

    // Post-race digest
    if (lastRace) {
      const daysSince = Math.ceil((nowMs - new Date(lastRace.raceDate).getTime()) / (1000 * 60 * 60 * 24));
      if (daysSince >= 0 && daysSince <= 4 && !alreadyCovered(recentAutoTitles, lastRace.name + " Reaction")) {
        const leader = top3Drivers[0];
        const second = top3Drivers[1];
        const topTeam = top2Constructors[0];
        candidates.push({
          title: `${lastRace.name} Reaction: Championship Standings After Round ${lastRace.round}`,
          excerpt: `The ${lastRace.name} has concluded. Here is how the 2026 World Championship looks after ${ordinal(lastRace.round)} round of racing.`,
          imageUrl: IMGS.track,
          tags: [lastRace.country, "Standings", "2026 Season", lastRace.name],
          sortOrder: 1,
          content: `The ${lastRace.name} at ${lastRace.circuit} has written its chapter in the 2026 Formula 1 World Championship. As teams debrief and prepare for the next round, here is the complete picture of the championship standings.\n\n## Drivers' Championship\n\n${top3Drivers.map((d, i) => `**${ordinal(i + 1)}. ${d.driverName} (${d.teamName}) — ${d.points} pts**`).join("\n")}\n\n${leader && second ? `${leader.driverName} leads ${second.driverName} by ${leader.points - second.points} points. With ${upcoming.length} rounds remaining, the championship ${leader.points - second.points < 25 ? "remains wide open" : "is taking shape but is far from decided"}.` : ""}\n\n## Constructors' Championship\n\n${top2Constructors.map((c, i) => `**${ordinal(i + 1)}. ${c.teamName} — ${c.points} pts**`).join("\n")}\n\n${topTeam ? `${topTeam.teamName} lead the Constructors' standings.` : ""}\n\n${upcoming.length > 0 ? `Next up: **${upcoming[0].name}** at ${upcoming[0].circuit}${upcoming[0].raceDate ? `, ${formatDate(upcoming[0].raceDate)}` : ""}.` : ""}`,
        });
      }
    }

    // Mid-week standings (Tue/Wed)
    if (today.getDay() === 2 || today.getDay() === 3) {
      const weekAgo = new Date(today.getTime() - 7 * 24 * 60 * 60 * 1000);
      const standingsThisWeek = allArticles.some((a: any) => {
        const dateField = a.publishedAt || a.createdAt;
        return dateField && new Date(dateField) > weekAgo && a.authorId === ADMIN_ID && (a.title || "").toLowerCase().includes("standings");
      });
      if (!standingsThisWeek && top3Drivers.length > 0) {
        const leader = top3Drivers[0];
        const second = top3Drivers[1];
        const third = top3Drivers[2];
        candidates.push({
          title: `2026 F1 Standings: Full Championship Picture After Round ${completed.length}`,
          excerpt: `Where does every driver and team stand in the 2026 Formula 1 World Championship? Complete standings breakdown after ${completed.length} rounds.`,
          imageUrl: IMGS.data,
          tags: ["Standings", "2026 Season", "Championship"],
          sortOrder: 1,
          content: `With ${completed.length} rounds completed and ${upcoming.length} to go in the 2026 Formula 1 World Championship, here is the complete standings picture.\n\n## Drivers — Top 10\n\n${drivers.slice(0, 10).map((d, i) => `**${ordinal(i + 1)}. ${d.driverName} ${d.flagEmoji || ""} (${d.teamName}) — ${d.points} pts${d.wins > 0 ? ` | ${d.wins} win${d.wins > 1 ? "s" : ""}` : ""}`).join("\n")}\n\n${leader && second ? `Gap: ${leader.points - second.points} points between ${leader.driverName} and ${second.driverName}. ${third ? `${third.driverName} is ${second.points - third.points} further back in third.` : ""}` : ""}\n\n## Constructors\n\n${constructors.map((c, i) => `**${ordinal(i + 1)}. ${c.teamName} — ${c.points} pts**`).join("\n")}\n\n${upcoming.length > 0 ? `Next race: **${upcoming[0].name}** at ${upcoming[0].circuit}${upcoming[0].raceDate ? ` on ${formatDate(upcoming[0].raceDate)}` : ""}.` : ""}`,
        });
      }
    }

    // Technical evergreen topics — fill remaining slots
    for (const topic of TECHNICAL_TOPICS) {
      if (!alreadyCovered(recentAutoTitles, topic.keyword)) {
        candidates.push({
          title: topic.title,
          excerpt: topic.content.split("\n")[0].substring(0, 200) + "...",
          imageUrl: topic.imageUrl,
          tags: topic.tags,
          sortOrder: 1,
          content: topic.content,
        });
      }
    }

    if (candidates.length === 0) {
      const nextRaceName = upcoming[0]?.name || "the next race";
      return {
        success: false,
        submitted: [],
        skipped: 0,
        noContent: true,
        message: `All technical topics have been published recently and no race event is imminent. New race content will be available closer to ${nextRaceName}.`,
      };
    }

    // Pick up to `remaining` unique candidates (deduplicated by title within this batch)
    const batch = candidates.slice(0, remaining);
    const submitted: string[] = [];

    for (const candidate of batch) {
      const article = await storage.submitArticle({
        title: candidate.title,
        excerpt: candidate.excerpt,
        content: candidate.content,
        authorId: ADMIN_ID,
        section: "news",
        tags: candidate.tags,
        sortOrder: candidate.sortOrder,
        imageUrl: candidate.imageUrl,
      });
      submitted.push(article.title);
    }

    return {
      success: true,
      submitted,
      skipped: Math.max(0, count - candidates.length),
      noContent: candidates.length < count,
      message: candidates.length < count
        ? `Generated ${submitted.length} article(s) — ${count - candidates.length} slot(s) had no fresh content available.`
        : undefined,
    };
  } catch (err: any) {
    return {
      success: false,
      submitted: [],
      skipped: 0,
      noContent: false,
      message: err?.message || "Unknown error during auto-publish batch",
    };
  }
}

// Legacy single-article wrapper used by scheduler if needed
export async function generateAndPublishArticle(): Promise<{
  success: boolean;
  title?: string;
  message?: string;
  noContent?: boolean;
}> {
  const result = await generateAndPublishBatch(1);
  if (result.success && result.submitted.length > 0) {
    return { success: true, title: result.submitted[0] };
  }
  return { success: false, noContent: result.noContent, message: result.message };
}
