import { storage } from "./storage";

const ADMIN_ID = "seed-admin";

function toSlugSimple(title: string): string {
  return title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}

// F1 evergreen topics — used when no race weekend is imminent
const EVERGREEN_TOPICS = [
  {
    keyword: "DRS",
    title: "DRS Explained: How Formula 1's Overtaking Aid Changed Racing Forever",
    tags: ["Technical", "DRS", "Overtaking", "Explainer"],
    content: `The Drag Reduction System — universally known by its acronym DRS — is one of the most debated pieces of technology in modern Formula 1. Introduced in 2011 as a deliberate mechanism to increase overtaking, it has been celebrated for producing more on-track action and criticised for making passes too easy.\n\nThe system works by allowing the driver following within one second of the car ahead to open a flap in the rear wing, reducing aerodynamic drag and increasing straight-line speed by approximately 10-15 km/h. In that window, the following driver can close the gap enough to attempt an overtake into the next braking zone.\n\nDRS zones are designated by the FIA before each race weekend based on the circuit layout. Most tracks have one or two zones, positioned on the longest straights where top speed has the greatest effect. Monza, with its multiple long straights, has historically offered the most DRS opportunity on the calendar.\n\nThe system can only be activated after the second lap of the race and after a safety car period, ensuring drivers have settled into racing conditions before artificial aids are deployed. In qualifying, drivers can use DRS freely throughout their lap without the one-second restriction.\n\nCritics have argued that DRS has transformed some overtakes from genuinely achieved passes into foregone conclusions — a driver simply pressing a button to sail past on the straight with no defensive option available. Proponents counter that without it, the aerodynamic turbulence generated by modern F1 cars would make following at close range nearly impossible, eliminating wheel-to-wheel racing entirely.\n\nThe 2022 regulation changes, which introduced ground-effect aerodynamics designed to reduce the dirty air problem, were partly intended to eventually reduce reliance on DRS. The discussion about phasing out the system continues in the paddock to this day, and with 2026's new regulations now bedded in, the future of DRS remains one of the sport's most active technical debates.`,
  },
  {
    keyword: "Pit Wall",
    title: "Inside the F1 Pit Wall: The Strategists Who Win Races From a Laptop",
    tags: ["Strategy", "Technical", "Behind the Scenes"],
    content: `For every driver who wins a Formula 1 race on track, there is a team of strategists behind a bank of screens on the pit wall who made it possible. Understanding how the pit wall works — and the decisions it makes under pressure — is essential to understanding the modern sport.\n\nThe race strategist's primary tool is their tyre model. Every team runs sophisticated software that predicts, lap by lap, how their tyres will degrade and what pace the car will be capable of at any given point in the race. This model is fed by live telemetry from the car, historical degradation data from previous races at the same circuit, and the weather feed from trackside sensors.\n\nFrom this data, the strategist constructs multiple race scenarios before lights out — a one-stop strategy, a two-stop, an alternative compound sequence — and ranks them by projected finishing position. As the race develops and variables change (safety cars, weather shifts, rival strategies), the model is updated in real time and the strategist communicates through the driver's ear.\n\nThe most critical moments are those that cannot be pre-planned: the unexpected safety car, the rival who pits a lap earlier than predicted, the sudden rain shower. In these moments, the strategist has seconds to make calls that could determine the championship. The best in the business — people like Andrew Shovlin at Mercedes or Ranaldo Gugelmin at McLaren — make these calls with a combination of data confidence and instinct that takes years to develop.\n\nDrivers and strategists don't always agree. The pit wall might instruct a driver to hold position to protect a tyre, while the driver — feeling the pace of the car behind — wants to push. Managing that communication, keeping the driver informed and aligned with the strategy, is as important as the numbers on the screen.\n\nIn a modern F1 race, the margin between first and fourth can be as small as a single strategic call made correctly under pressure. The pit wall is where championships are decided.`,
  },
  {
    keyword: "Tyre Compounds",
    title: "Pirelli's F1 Tyre Compounds Explained: From Soft to Hard and Everything Between",
    tags: ["Technical", "Tyres", "Pirelli", "Explainer"],
    content: `Pirelli has been Formula 1's sole tyre supplier since 2011, and the Italian manufacturer's compounds have been one of the defining elements of race strategy throughout that period. Understanding how the tyre range works is fundamental to understanding why races unfold the way they do.\n\nFor each grand prix, Pirelli nominates three compounds from their range — designated C1 through C5, where C1 is the hardest and C5 the softest. These are then labelled for race weekend use as Hard, Medium, and Soft respectively. The specific selection varies by circuit: at high-energy tracks like Silverstone, Pirelli typically brings harder compounds; at lower-stress circuits like Monaco, softer compounds are used.\n\nThe trade-off is straightforward in principle, complex in execution. Softer compounds generate more grip and therefore more pace, but their rubber degrades faster as they heat and wear. Harder compounds sacrifice some outright pace for greater durability — they can cover significantly more laps before their performance falls off a cliff.\n\nThe degradation model is not linear. Tyres typically go through three phases: a warming phase where performance builds, a performance peak, and then a degradation phase that can vary from gradual (a tyre that "drops off" slowly) to sudden (a "cliff" where grip disappears dramatically in a single lap). Predicting and managing this cliff is one of the most demanding aspects of race strategy.\n\nThermal management — keeping the tyre within its optimal operating temperature window — is a constant challenge. Too cold, and the rubber doesn't generate sufficient grip. Too hot, and the tyre blisters and degrades rapidly. Factors including track surface, ambient temperature, driving style, and car setup all influence tyre temperature.\n\nThe introduction of 18-inch wheels in 2022, replacing the 13-inch wheels used since the early days of the sport, changed the thermal properties of F1 tyres significantly. The lower-profile construction of the new tyres runs cooler and is less prone to the dramatic overheating that characterised some of the most dramatic tyre failures of the earlier era.`,
  },
  {
    keyword: "Downforce",
    title: "Downforce: The Invisible Force That Makes F1 Cars Defy Physics",
    tags: ["Technical", "Aerodynamics", "Explainer"],
    content: `A modern Formula 1 car generates more aerodynamic downforce than its own weight. At racing speeds, the aerodynamic load pressing the car into the ground exceeds the force of gravity acting upon it. In theoretical terms, at sufficient speed, an F1 car could drive upside down on the ceiling of a tunnel and stay there.\n\nThis extraordinary capability is the result of decades of aerodynamic development and represents one of the most complex engineering challenges in any form of motorsport. Understanding downforce — where it comes from, how it is generated, and why it comes at a cost — is essential to understanding how F1 cars work.\n\nDownforce is generated primarily by the interaction between airflow and shaped surfaces. The wings at the front and rear of the car function as inverted aerofoils — the same principle as an aircraft wing, but inverted to generate downward force rather than lift. The angle of these wings (their "angle of attack") determines how much downforce they generate, but also how much drag they create.\n\nThis is the fundamental compromise at the heart of F1 car design: more downforce means more corner grip and faster lap times through high-speed sections, but also more drag and slower straight-line speed. Every circuit demands a different balance. At Monza, teams run minimum downforce for maximum top speed. At Monaco, maximum downforce is required for the slow, technical corners.\n\nThe 2022 regulations represented a revolution in how downforce is generated. Previous cars relied heavily on complex front wing endplates and bargeboards to control airflow across the car. The new ground-effect regulations largely moved the downforce generation beneath the car, through shaped underfloor channels that accelerate and redirect air to create an area of low pressure under the car — sucking it downwards.\n\nGround-effect downforce is considered more efficient than wing-generated downforce because it creates less drag for equivalent grip levels. It also addresses one of the biggest problems in modern F1: the dirty air generated by cars with complex upper surfaces disrupted following cars enormously. The ground-effect floor is less affected by disturbed air, allowing cars to follow more closely — which is why overtaking improved significantly after 2022.`,
  },
  {
    keyword: "F1 Budget Cap",
    title: "The F1 Cost Cap Explained: How the $135 Million Limit Reshaped the Paddock",
    tags: ["Regulations", "Budget Cap", "Business of F1"],
    content: `When Formula 1 introduced a financial cost cap in 2021, it represented the most significant structural change to the sport's economics in its history. The intent was simple: prevent the wealthiest teams from spending their way to dominance, and create conditions where technical excellence and innovation mattered more than raw financial firepower.\n\nThe cap limits the amount teams can spend on "performance-related" costs — essentially, anything directly connected to developing and racing the car. The figure has been set at varying levels since introduction, accounting for inflation and indexed adjustments, sitting in the region of $135 million for the current cycle.\n\nCrucially, certain costs are excluded from the cap. Driver salaries (above a threshold), the salaries of the three highest-paid staff members, marketing costs, and the CEO's salary are all excluded. This means the total spending at a top team remains significantly higher than the headline cap figure, but the excluded categories are not directly performance-related.\n\nThe FIA enforces the cap through detailed financial scrutiny, requiring teams to submit audited accounts and working closely with teams to classify expenditures correctly. The process has not been without controversy — Red Bull Racing's breach of the 2021 cap, which was found to exceed the limit by a relatively small margin, resulted in a significant fine and aerodynamic testing penalty that reverberated through the sport.\n\nThe impact on the midfield has been arguably the cap's most transformative effect. Teams that previously operated on modest budgets have found that the cap level now represents an increase in their available resources, allowing them to develop more sophisticated cars than before. The bunching of the grid in terms of competitiveness — with far smaller gaps between teams than existed before 2021 — is widely attributed, at least in part, to the financial regulations.\n\nAs the sport continues to grow commercially, with team valuations reaching figures that would have seemed extraordinary a decade ago, the cost cap has become a pillar of the sporting framework. Its long-term impact on the competitive order continues to play out with every race.`,
  },
];

function getDayOfYear(date: Date): number {
  const start = new Date(date.getFullYear(), 0, 0);
  const diff = date.getTime() - start.getTime();
  return Math.floor(diff / (1000 * 60 * 60 * 24));
}

function formatDate(dateStr: string): string {
  const d = new Date(dateStr);
  return d.toLocaleDateString("en-GB", { weekday: "long", day: "numeric", month: "long", year: "numeric" });
}

function ordinal(n: number): string {
  const s = ["th", "st", "nd", "rd"];
  const v = n % 100;
  return n + (s[(v - 20) % 10] || s[v] || s[0]);
}

export async function generateAndPublishArticle(): Promise<{ success: boolean; title?: string; message?: string }> {
  try {
    const today = new Date();
    const todayStr = today.toISOString().split("T")[0];

    // Check if we already auto-submitted/published today (check both published and pending queues)
    const [existing, pending] = await Promise.all([storage.getArticles(), storage.getPendingArticles()]);
    const allToCheck = [...existing, ...pending];
    const alreadyToday = allToCheck.some((a: any) => {
      const pub = a.publishedAt || a.createdAt;
      const pubDate = pub ? new Date(pub).toISOString().split("T")[0] : "";
      return pubDate === todayStr && a.authorId === ADMIN_ID;
    });
    if (alreadyToday) {
      return { success: false, message: "An article was already auto-submitted today." };
    }

    // Get races and standings
    const races = await storage.getAllRaces(2026);
    const drivers = await storage.getDriverStandings(2026);
    const constructors = await storage.getConstructorStandings(2026);

    const nowMs = today.getTime();
    const upcoming = races
      .filter(r => r.status === "upcoming" || r.status === "live")
      .sort((a, b) => new Date(a.raceDate).getTime() - new Date(b.raceDate).getTime());
    const completed = races
      .filter(r => r.status === "completed")
      .sort((a, b) => new Date(b.raceDate).getTime() - new Date(a.raceDate).getTime());

    const nextRace = upcoming[0];
    const lastRace = completed[0];
    const top3Drivers = drivers.slice(0, 3);
    const top2Constructors = constructors.slice(0, 2);

    let articleData: { title: string; excerpt: string; content: string; tags: string[]; sortOrder: number } | null = null;

    // Priority 1: Race preview if race is within 7 days
    if (nextRace) {
      const raceDayMs = new Date(nextRace.raceDate).getTime();
      const daysUntil = Math.ceil((raceDayMs - nowMs) / (1000 * 60 * 60 * 24));

      if (daysUntil >= 0 && daysUntil <= 7) {
        const leader = top3Drivers[0];
        const second = top3Drivers[1];
        const ptsDiff = leader && second ? leader.points - second.points : 0;
        const topConstructor = top2Constructors[0];

        const driverBattle = leader && second
          ? `${leader.driverName} leads the Drivers' Championship with ${leader.points} points, ${ptsDiff} ahead of ${second.driverName}.`
          : "";
        const teamBattle = topConstructor
          ? `In the Constructors' standings, ${topConstructor.teamName} lead the way with ${topConstructor.points} points.`
          : "";

        articleData = {
          title: `${nextRace.name} Preview: Everything You Need to Know Ahead of Round ${nextRace.round}`,
          excerpt: `Formula 1 heads to ${nextRace.location}, ${nextRace.country} for the ${nextRace.name}. With the championship picture sharpening, this could be a pivotal weekend. Here is everything you need to know.`,
          tags: [nextRace.country, "Race Preview", "2026 Season", nextRace.name],
          sortOrder: 10,
          content: `Formula 1 returns to action this weekend at ${nextRace.circuit} in ${nextRace.location}, ${nextRace.country} for the ${nextRace.name} — Round ${ordinal(nextRace.round)} of the 2026 World Championship. ${nextRace.hasSprint ? "This is a Sprint weekend, with an additional Sprint race on Saturday that adds a further 8 points to the championship tally." : ""}\n\n## The Championship Situation\n\n${driverBattle} ${teamBattle} With ${upcoming.length} rounds remaining after this weekend, every point counts and the pressure on the drivers to perform will be intense.\n\n## Circuit Profile: ${nextRace.circuit}\n\nLocated in ${nextRace.location}, ${nextRace.country}, the ${nextRace.circuit} is one of the most demanding venues on the 2026 calendar. The track rewards a precise setup balance between downforce for the technical sections and aerodynamic efficiency for the straights. Getting tyre management right will be critical — teams will be carefully studying their compounds allocation for this event in the days leading up to qualifying.\n\n## Key Questions Heading In\n\nWhich team has found the better setup direction this weekend? Can the championship leader maintain their form under the pressure of a rival closing in? Will the circuit characteristics suit any particular team's car concept in a way that could upset the expected order?\n\nThe answers begin on Friday morning when Practice 1 gets underway. ${nextRace.raceDate ? `The race starts on ${formatDate(nextRace.raceDate)}.` : ""}\n\n## How to Follow the Action\n\nFull live coverage and race analysis will be available here on F1 Fan Hub throughout the weekend. Check back for qualifying reaction, race preview updates, and post-race reports as soon as the chequered flag falls.`,
        };
      }
    }

    // Priority 2: Post-race review if race completed within last 4 days
    if (!articleData && lastRace) {
      const raceMs = new Date(lastRace.raceDate).getTime();
      const daysSince = Math.ceil((nowMs - raceMs) / (1000 * 60 * 60 * 24));

      if (daysSince >= 0 && daysSince <= 4) {
        const leader = top3Drivers[0];
        const second = top3Drivers[1];
        const topTeam = top2Constructors[0];

        articleData = {
          title: `${lastRace.name} Reaction: How the Standings Look After Round ${lastRace.round}`,
          excerpt: `With the ${lastRace.name} in the books, we take stock of the championship picture. Here is how the 2026 season standings look after ${ordinal(lastRace.round)} round.`,
          tags: [lastRace.country, "Standings", "2026 Season", lastRace.name],
          sortOrder: 10,
          content: `The ${lastRace.name} at ${lastRace.circuit} has added another chapter to the 2026 Formula 1 season story. As the paddock takes stock after ${ordinal(lastRace.round)} round, the championship picture is beginning to take shape.\n\n## How the Drivers' Championship Stands\n\n${top3Drivers.map((d, i) => `**${ordinal(i + 1)}. ${d.driverName} (${d.teamName}) — ${d.points} points**`).join("\n")}\n\n${leader && second ? `${leader.driverName} holds ${leader.points - second.points} points of advantage over ${second.driverName} as the season progresses. The gap ${leader.points - second.points < 10 ? "remains tight enough that a single bad weekend could change everything" : "gives the championship leader some breathing room, but nothing is settled yet"}.` : ""}\n\n## The Constructors' Battle\n\n${top2Constructors.map((c, i) => `**${ordinal(i + 1)}. ${c.teamName} — ${c.points} points**`).join("\n")}\n\n${topTeam ? `${topTeam.teamName} lead the Constructors' Championship, a reflection of consistent points scoring from both drivers throughout the opening rounds.` : ""}\n\n## Looking Ahead\n\n${upcoming.length > 0 ? `The next round is the ${upcoming[0].name} at ${upcoming[0].circuit} in ${upcoming[0].location}. With ${upcoming.length} races still to run, the 2026 championship remains very much in play for multiple contenders.` : "The 2026 season continues to build towards what promises to be a dramatic conclusion."}\n\nKeep up with all the action here on F1 Fan Hub — analysis, race previews, and live standings updates throughout the 2026 campaign.`,
        };
      }
    }

    // Priority 3: Midweek standings digest (Tuesday/Wednesday)
    if (!articleData && (today.getDay() === 2 || today.getDay() === 3) && top3Drivers.length > 0) {
      const leader = top3Drivers[0];
      const second = top3Drivers[1];
      const third = top3Drivers[2];

      articleData = {
        title: `2026 F1 Championship Standings: Where Every Driver and Team Stands Now`,
        excerpt: `The 2026 Formula 1 season is underway. Here is a full breakdown of the Drivers' and Constructors' Championship standings as they look right now.`,
        tags: ["Standings", "2026 Season", "Championship"],
        sortOrder: 10,
        content: `With ${completed.length} rounds of the 2026 Formula 1 World Championship completed and ${upcoming.length} still to come, the picture is becoming clearer — though the outcome remains far from decided. Here is a comprehensive look at exactly where every driver and team stands.\n\n## Drivers' Championship — Top 10\n\n${drivers.slice(0, 10).map((d, i) => `**${ordinal(i + 1)}. ${d.driverName} ${d.flagEmoji || ""} (${d.teamName}) — ${d.points} pts${d.wins > 0 ? ` | ${d.wins} win${d.wins > 1 ? "s" : ""}` : ""}`).join("\n")}\n\n${leader && second ? `The gap between ${leader.driverName} and ${second.driverName} currently stands at ${leader.points - second.points} points — the equivalent of ${Math.ceil((leader.points - second.points) / 25)} race victories at maximum score. ${third ? `${third.driverName} is a further ${second.points - third.points} back in third.` : ""}` : ""}\n\n## Constructors' Championship\n\n${constructors.map((c, i) => `**${ordinal(i + 1)}. ${c.teamName} — ${c.points} pts`).join("\n")}\n\n## Season in Numbers\n\n- Rounds completed: ${completed.length}\n- Rounds remaining: ${upcoming.length}\n- Total points available: ${upcoming.length * 44} (race + sprint rounds)\n\n${upcoming.length > 0 ? `The next race is the **${upcoming[0].name}** at ${upcoming[0].circuit}${upcoming[0].raceDate ? ` on ${formatDate(upcoming[0].raceDate)}` : ""}.` : ""}\n\nF1 Fan Hub will keep this page updated as the season develops — check back after every race for the latest standings.`,
      };
    }

    // Priority 4: Evergreen topic rotation
    if (!articleData) {
      const dayIndex = getDayOfYear(today) % EVERGREEN_TOPICS.length;
      const topic = EVERGREEN_TOPICS[dayIndex];
      articleData = {
        title: topic.title,
        excerpt: topic.content.split("\n")[0].substring(0, 180) + "...",
        tags: topic.tags,
        sortOrder: 30,
        content: topic.content,
      };
    }

    // Submit for admin review (pending status) so it can be previewed before approval
    const submitted = await storage.submitArticle({
      title: articleData.title,
      excerpt: articleData.excerpt,
      content: articleData.content,
      authorId: ADMIN_ID,
      section: "news",
      tags: articleData.tags,
      sortOrder: articleData.sortOrder,
      imageUrl: null,
    });

    return { success: true, title: submitted.title };
  } catch (err: any) {
    return { success: false, message: err?.message || "Unknown error" };
  }
}
